export const envSchema = {
  type: "object",
  required: [
    "BACKEND_INTERNAL_PORT",
    "JWT_AUTH_SECRET",
    "JWT_COMMON_SECRET",
    "DB_CONNECTION_STRING",
    "MAIL_HOST",
    "MAIL_PORT",
    "MAIL_USER",
    "MAIL_PASS",
    "MAIL_FROM",
    "VERIFY_EMAIL_BASE_URL",
    "RESET_PASSWORD_BASE_URL",
    "S3_ACCESS_KEY_ID",
    "S3_SECRET_ACCESS_KEY",
    "S3_BUCKET",
    "S3_BUCKET_IMAGES",
    "FRONTEND_EXTERNAL_BASE_URL",
    "STRIPE_PUBLIC_KEY",
    "STRIPE_SECRET_KEY",
    "STRIPE_WEBHOOK_SECRET_KEY",
    "STRIPE_PRODUCT_ID",
    "BILLING_PRICE_UNIT_AMOUNT_DECIMAL",
    "BILLING_RECURRING_INTERVAL",
    "BILLING_RECURRING_INTERVAL_COUNT",
    "BILLING_DAYS_AFTER_CANCELING_SUBSCRIPTION",
    "BILLING_DAYS_OF_TRIAL",
    "BILLING_DAYS_BEFORE_NOTIFICATION_OF_TRIAL_ENDING",
    "LIMIT_FROM_LAST_INVITATION_IN_MINUTES",
    "TEST_LIMIT_FROM_LAST_INVITATION_IN_MINUTES",
    "MAIL_SERVICE_TEST_MODE",
    "MAIL_SUPPORT_EMAIL",
    "BCC_INVITATION_DELAY_DEFAULT",
    "BCC_INVITATION_DELAY_MAX",
    "CLOUD_WATCH_LOGS_ACCESS_KEY_ID",
    "CLOUD_WATCH_LOGS_REGION",
    "CLOUD_WATCH_LOGS_SECRET_ACCESS_KEY",
    "CLOUD_WATCH_LOGS_GROUP_NAME",
    "CLOUD_WATCH_LOGS_RECORDS_LIMIT",
    "CLOUD_WATCH_LOGS_TO_EMAIL",
    "CLOUD_WATCH_LOGS_START_SECONDS_OFFSET",
    "INVITATION_REMINDER_DELAY_DEFAULT",
    "INVITATION_REMINDER_DELAY_MAX",
    "INVITATION_REMINDER_DELAY_MIN",
    "STRIPE_TEST_PRICE_ID",
    "STRIPE_TEST_WEBHOOK_SECRET_KEY",
    "STRIPE_TEST_SECRET_KEY",
    "STRIPE_TEST_DEFAULT_TAX_RATE",
  ],
  properties: {
    BACKEND_INTERNAL_PORT: { type: "string" },
    JWT_AUTH_SECRET: { type: "string" },
    JWT_COMMON_SECRET: { type: "string" },
    DB_CONNECTION_STRING: { type: "string" },
    MAIL_HOST: { type: "string" },
    MAIL_PORT: { type: "number" },
    MAIL_USER: { type: "string" },
    MAIL_PASS: { type: "string" },
    MAIL_FROM: { type: "string" },
    VERIFY_EMAIL_BASE_URL: { type: "string" },
    RESET_PASSWORD_BASE_URL: { type: "string" },
    S3_ACCESS_KEY_ID: { type: "string" },
    S3_SECRET_ACCESS_KEY: { type: "string" },
    S3_BUCKET: { type: "string" },
    S3_BUCKET_IMAGES: { type: "string" },
    DEBUG: { type: "string" },
    FRONTEND_EXTERNAL_BASE_URL: { type: "string" },
    STRIPE_PUBLIC_KEY: { type: "string" },
    STRIPE_SECRET_KEY: { type: "string" },
    STRIPE_WEBHOOK_SECRET_KEY: { type: "string" },
    STRIPE_PRODUCT_ID: { type: "string" },
    BILLING_PRICE_UNIT_AMOUNT_DECIMAL: { type: "number" },
    BILLING_RECURRING_INTERVAL: {
      type: "string",
      enum: ["day", "month", "week", "year"],
    },
    BILLING_RECURRING_INTERVAL_COUNT: { type: "number" },
    BILLING_DEFAULT_TAX_RATE: { type: "string" },
    BILLING_DAYS_AFTER_CANCELING_SUBSCRIPTION: { type: "number" },
    BILLING_DAYS_OF_TRIAL: { type: "number" },
    BILLING_DAYS_BEFORE_NOTIFICATION_OF_TRIAL_ENDING: { type: "number" },
    LIMIT_FROM_LAST_INVITATION_IN_MINUTES: { type: "number" },
    TEST_LIMIT_FROM_LAST_INVITATION_IN_MINUTES: { type: "number", default: 2 },
    MAIL_SERVICE_TEST_MODE: { type: "boolean" },
    MAIL_SUPPORT_EMAIL: { type: "string" },
    BCC_INVITATION_DELAY_DEFAULT: { type: "number" },
    BCC_INVITATION_DELAY_MAX: { type: "number" },
    CLOUD_WATCH_LOGS_ACCESS_KEY_ID: { type: "string" },
    CLOUD_WATCH_LOGS_REGION: { type: "string" },
    CLOUD_WATCH_LOGS_SECRET_ACCESS_KEY: { type: "string" },
    CLOUD_WATCH_LOGS_GROUP_NAME: { type: "string" },
    CLOUD_WATCH_LOGS_RECORDS_LIMIT: { type: "number" },
    CLOUD_WATCH_LOGS_TO_EMAIL: { type: "string" },
    CLOUD_WATCH_LOGS_START_SECONDS_OFFSET: { type: "number" },
    INVITATION_REMINDER_DELAY_MAX: { type: "number" },
    INVITATION_REMINDER_DELAY_DEFAULT: { type: "number" },
    INVITATION_REMINDER_DELAY_MIN: { type: "number" },
    STRIPE_TEST_PRICE_ID: { type: "string" },
    STRIPE_TEST_WEBHOOK_SECRET_KEY: { type: "string" },
    STRIPE_TEST_SECRET_KEY: { type: "string" },
    STRIPE_TEST_DEFAULT_TAX_RATE: { type: "string" },
  },
} as const;
