version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
      args:
        # For production
        - ARG_VITE_API_FRONTEND_BASE_URL=$VITE_API_FRONTEND_BASE_URL
        - ARG_VITE_API_BACKEND_BASE_URL=$VITE_API_BACKEND_BASE_URL
        - ARG_VITE_GOOGLE_API_KEY=$VITE_GOOGLE_API_KEY
        - ARG_VITE_GOOGLE_ANALYTICS_KEY=$VITE_GOOGLE_ANALYTICS_KEY
        - ARG_VITE_FRONTEND_EXTERNAL_BASE_URL=$FRONTEND_EXTERNAL_BASE_URL
        - ARG_VITE_BCC_EMAIL=$BCC_EMAIL
        - ARG_VITE_STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY
        - ARG_VITE_LIVECHAT_LICENSE=$LIVECHAT_LICENSE
        - ARG_VITE_BILLING_DAYS_AFTER_CANCELING_SUBSCRIPTION=$BILLING_DAYS_AFTER_CANCELING_SUBSCRIPTION
        - ARG_VITE_BILLING_PRICE_UNIT_AMOUNT_DECIMAL=$BILLING_PRICE_UNIT_AMOUNT_DECIMAL
        - ARG_VITE_BILLING_RECURRING_INTERVAL=$BILLING_RECURRING_INTERVAL
        - ARG_VITE_BILLING_RECURRING_INTERVAL_COUNT=$BILLING_RECURRING_INTERVAL_COUNT
        - ARG_VITE_DEFAULT_PAGE_TITLE=$VITE_DEFAULT_PAGE_TITLE
        - ARG_VITE_CSV_EMAILS_LIMIT=$VITE_CSV_EMAILS_LIMIT
        - ARG_VITE_FINGERPRINT_PUBLIC_TOKEN=$VITE_FINGERPRINT_PUBLIC_TOKEN
        - ARG_VITE_FINGERPRINT_SUBDOMAIN_URL=$VITE_FINGERPRINT_SUBDOMAIN_URL
        - ARG_VITE_FINGERPRINT_COUNTRY_CODES=$VITE_FINGERPRINT_COUNTRY_CODES
        - ARG_VITE_HELPDESK_LICENSE_ID=$VITE_HELPDESK_LICENSE_ID
        - ARG_VITE_HELPDESK_CONTACT_FORM_ID=$VITE_HELPDESK_CONTACT_FORM_ID
        - ARG_VITE_BCC_INVITATION_DELAY_MAX=$BCC_INVITATION_DELAY_MAX
    volumes:
      - ./frontend/src:/home/node/app/frontend/src
    expose:
      - ${FRONTEND_INTERNAL_PORT}
      - 24678
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}
      - 24678:24678 # Vite dev server websocket for hot reload
    environment:
      # For development
      - VITE_API_FRONTEND_BASE_URL
      - VITE_API_BACKEND_BASE_URL
      - FRONTEND_INTERNAL_PORT
      - BACKEND_ROUTE_PREFIX
      - VITE_GOOGLE_API_KEY
      - VITE_FRONTEND_EXTERNAL_BASE_URL=$FRONTEND_EXTERNAL_BASE_URL
      - VITE_BCC_EMAIL=$BCC_EMAIL
      - VITE_STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY
      - VITE_LIVECHAT_LICENSE=$LIVECHAT_LICENSE
      - VITE_BILLING_DAYS_AFTER_CANCELING_SUBSCRIPTION=$BILLING_DAYS_AFTER_CANCELING_SUBSCRIPTION
      - VITE_BILLING_PRICE_UNIT_AMOUNT_DECIMAL=$BILLING_PRICE_UNIT_AMOUNT_DECIMAL
      - VITE_BILLING_RECURRING_INTERVAL=$BILLING_RECURRING_INTERVAL
      - VITE_BILLING_RECURRING_INTERVAL_COUNT=$BILLING_RECURRING_INTERVAL_COUNT
      - VITE_DEFAULT_PAGE_TITLE
      - VITE_GOOGLE_ANALYTICS_KEY
      - VITE_CSV_EMAILS_LIMIT
      - VITE_FINGERPRINT_PUBLIC_TOKEN
      - VITE_FINGERPRINT_SUBDOMAIN_URL
      - VITE_FINGERPRINT_COUNTRY_CODES
      - VITE_HELPDESK_LICENSE_ID
      - VITE_HELPDESK_CONTACT_FORM_ID
      - VITE_BCC_INVITATION_DELAY_MAX=$BCC_INVITATION_DELAY_MAX
      - VITE_INVITATION_REMINDER_DELAY_MAX=$INVITATION_REMINDER_DELAY_MAX
      - VITE_INVITATION_REMINDER_DELAY_MIN=$INVITATION_REMINDER_DELAY_MIN
    command: yarn dev
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dependencies
    volumes:
      - ./backend/src:/home/node/app/backend/src
      - ./backend/public-static:/home/node/app/backend/public-static
    expose:
      - ${BACKEND_INTERNAL_PORT}
    ports:
      - ${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}
    environment:
      - BACKEND_INTERNAL_PORT
      - FRONTEND_INTERNAL_PORT
      - FRONTEND_EXTERNAL_PORT
      - BACKEND_ROUTE_PREFIX
      - JWT_AUTH_SECRET
      - JWT_COMMON_SECRET
      - DB_CONNECTION_STRING
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USER
      - MAIL_PASS
      - MAIL_FROM
      - VERIFY_EMAIL_BASE_URL
      - RESET_PASSWORD_BASE_URL
      - FRONTEND_EXTERNAL_BASE_URL
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET
      - S3_BUCKET_IMAGES
      - DEBUG
      - STRIPE_PUBLIC_KEY
      - STRIPE_SECRET_KEY
      - STRIPE_WEBHOOK_SECRET_KEY
      - STRIPE_PRODUCT_ID
      - BILLING_PRICE_UNIT_AMOUNT_DECIMAL
      - BILLING_RECURRING_INTERVAL
      - BILLING_RECURRING_INTERVAL_COUNT
      - BILLING_DEFAULT_TAX_RATE
      - BILLING_DAYS_AFTER_CANCELING_SUBSCRIPTION
      - BILLING_DAYS_OF_TRIAL
      - BILLING_DAYS_BEFORE_NOTIFICATION_OF_TRIAL_ENDING
      - OWNER_PASSWORD
      - LIMIT_FROM_LAST_INVITATION_IN_MINUTES
      - MAIL_SERVICE_TEST_MODE
      - MAIL_SUPPORT_EMAIL
      - BCC_INVITATION_DELAY_MAX
      - BCC_INVITATION_DELAY_DEFAULT
      - CLOUD_WATCH_LOGS_REGION
      - CLOUD_WATCH_LOGS_ACCESS_KEY_ID
      - CLOUD_WATCH_LOGS_SECRET_ACCESS_KEY
      - CLOUD_WATCH_LOGS_GROUP_NAME
      - CLOUD_WATCH_LOGS_RECORDS_LIMIT
      - CLOUD_WATCH_LOGS_TO_EMAIL
      - CLOUD_WATCH_LOGS_START_SECONDS_OFFSET
      - INVITATION_REMINDER_DELAY_DEFAULT
      - INVITATION_REMINDER_DELAY_MAX
      - INVITATION_REMINDER_DELAY_MIN
      - STRIPE_TEST_PRICE_ID
      - STRIPE_TEST_WEBHOOK_SECRET_KEY
      - STRIPE_TEST_SECRET_KEY
      - STRIPE_TEST_DEFAULT_TAX_RATE
    command: yarn dev
    restart: always
    depends_on:
      - mongo
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://backend:3001/health-check || exit 1

  mongo:
    image: mongo
    container_name: mcr-dev-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

volumes:
  mongo_data:
