version: '3.9'

services:
  frontend:
    image: 229425579640.dkr.ecr.ap-southeast-2.amazonaws.com/mcr_frontend:stage
    build:
      target: production
    command: node ./dist/node-server/index.js

  backend:
    image: 229425579640.dkr.ecr.ap-southeast-2.amazonaws.com/mcr_backend:stage
    build:
      target: production
    command: node dist/index.js
