export const companyCategories = [
  "Animal Hospital",
  "Animal Rescue Service",
  "Animal Shelter",
  "Animal Watering Hole",
  "Emergency Veterinarian Service",
  "Sheep Shearer",
  "Veterinarian",
  "Animal Park",
  "Aquarium",
  "Bird Watching Area",
  "Wildlife and Safari Park",
  "Wildlife Park",
  "Wildlife Refuge",
  "Zoo",
  "Cat Hostel",
  "Cattery",
  "Dog Breeder",
  "Dog Cafe",
  "Dog Day Care Center",
  "Dog Hostel",
  "Dog Park",
  "Dog Trainer",
  "Dog Walker",
  "Kennel",
  "Horse Boarding Stable",
  "Horse Breeder",
  "Horse Rental Service",
  "Horse Riding Field",
  "Horse Riding School",
  "Horse Stable Stud Farm",
  "Horse Trainer",
  "Horse Transport Supplier",
  "Horseback Riding Service",
  "Horseshoe Smith",
  "Pony Club",
  "Pony Ride Service",
  "Saddlery",
  "Stable",
  "Agistment Service",
  "Animal Control Service",
  "Pet Adoption Service",
  "Pet Boarding Service",
  "Pet Cemetery",
  "Pet Funeral Service",
  "Pet Groomer",
  "Pet Moving Service",
  "Pet Sitter",
  "Pet Trainer",
  "Wildlife Rescue Service",
  "Animal Feed Store",
  "Aquarium Shop",
  "Bird Shop",
  "Goldfish Store",
  "Pet Store",
  "Pet Supply Store",
  "Reptile Store",
  "Tack Shop",
  "Tropical Fish Store",
  "Beauty Product Supplier",
  "Beauty Products Vending Machine",
  "Beauty Products Wholesaler",
  "Beauty Supply Store",
  "Cosmetic Products Manufacturer",
  "Cosmetics and Perfumes Supplier",
  "Cosmetics Industry",
  "Cosmetics Store",
  "Cosmetics Wholesaler",
  "Flavours",
  "Make-Up Artist",
  "Perfume Store",
  "Permanent Make-Up Clinic",
  "Skin Care Products Vending Machine",
  "Barber Shop",
  "Barber Supply Store",
  "Electrolysis Hair Removal Service",
  "Hair Extension Technician",
  "Hair Extensions Supplier",
  "Hair Product Store",
  "Hair Removal Service",
  "Hair Replacement Service",
  "Hair Salon",
  "Hair Transplantation Clinic",
  "Hairdresser",
  "Home Hairdresser",
  "Laser Hair Removal Service",
  "Mobile Hairdresser",
  "Waxing Hair Removal Service",
  "Fitness and Nutrition Service",
  "Herb Shop",
  "Herbalist",
  "Massage Supply Store",
  "Nail Salon",
  "Sleep Clinic",
  "Toiletries Store",
  "Vitamin and Supplements Store",
  "Weight Loss Service",
  "Beauty Salon",
  "Body Shaping Class",
  "Eyebrow bar",
  "Health and Beauty Shop",
  "Skin Care Clinic",
  "Stylist",
  "Tanning Salon",
  "Body Piercing Shop",
  "Ear-Piercing Service",
  "Mehandi Class",
  "Mehndi Designer",
  "Tattoo and Piercing Shop",
  "Tattoo Removal Service",
  "Tattoo Shop",
  "Aromatherapy Supply Store",
  "Day Spa",
  "Facial Spa",
  "Fish Spa",
  "Foot Bath",
  "Foot Care",
  "Foot Massage Parlor",
  "Hammam",
  "Health Spa",
  "Hot Bedstone Spa",
  "Massage Spa",
  "Massage Therapist",
  "Public Bath",
  "Public Sauna",
  "Sauna",
  "Sauna Club",
  "Sauna Store",
  "Spa",
  "Spa and Health Club",
  "Spa Garden",
  "Spa Resort",
  "Spa Town",
  "Super Public Bath",
  "Thermal Baths",
  "Wellness Center",
  "Wellness Program",
  "Bikram Yoga Studio",
  "Meditation Center",
  "Meditation Instructor",
  "Pilates Studio",
  "Yoga Instructor",
  "Yoga Retreat Center",
  "Yoga Studio",
  "Auditor",
  "BPO Company",
  "BPO Placement Agency",
  "Business Administration Service",
  "Business Broker",
  "Business Management Consultant",
  "Business to Business Service",
  "Card Processing Service",
  "Commercial Agent",
  "Consultant",
  "Corporate Entertainment Service",
  "Corporate Gift Supplier",
  "Debris Removal Service",
  "Distribution Service",
  "Eftpos Equipment Supplier",
  "Executive Search Firm",
  "Mapping Service",
  "Market Operator",
  "Payment Service",
  "Professional Organizer",
  "Security Guard Service",
  "Store Equipment Supplier",
  "Superannuation Consultant",
  "Typing Service",
  "Business Center",
  "Business Networking Company",
  "Business Park",
  "Chamber of Agriculture",
  "Chamber of Commerce",
  "Conference Center",
  "Convention Center",
  "Function Room Facility",
  "Applicant Tracking System",
  "Educational Consultant",
  "Employment Consultant",
  "Human Resource Consulting",
  "Payroll Service",
  "Recruiter",
  "Recruitment Service",
  "Talent Agency",
  "Temp Agency",
  "Clothing Exporter",
  "Cotton Exporter",
  "Electronics Exporter",
  "Equipment Exporter",
  "Equipment Importer",
  "Exporter",
  "Food and Beverage Exporter",
  "Foreign Trade Consultant",
  "Import Export Company",
  "Importer",
  "International Trade Consultant",
  "Jute Exporter",
  "Natural Stone Exporter",
  "Spices Exporter",
  "Textile Exporter",
  "Accounting Software Company",
  "Audio Transcription Service",
  "Automation Company",
  "Business and IT Consulting Agency",
  "Cloud Computing Service",
  "Cloud Storage Service",
  "Computer Consultant",
  "Computer Security Service",
  "Conference Calling Service",
  "Data Destruction Equipment Store",
  "Data Entry Service",
  "Data Recovery Service",
  "Database Management Company",
  "Drives and Storage Service",
  "e-Commerce Agency",
  "e-Commerce Service",
  "e-Commerce Solution Provider",
  "Establishment POI",
  "Fax Service",
  "Image Consultant",
  "Mailing Service",
  "Tower Communication Service",
  "Transcription Service",
  "Translator",
  "Video Conferencing Service",
  "Virtual Office Rental",
  "Web designer",
  "Website Designer",
  "Coin Operated Locker",
  "Commercial Cleaning Service",
  "Commercial Printer",
  "Commercial Real Estate Agency",
  "Commercial Real Estate Inspector",
  "Conference and Meeting Room Service",
  "Corporate Campus",
  "Corporate Office",
  "Coworking Space",
  "Envelope Supplier",
  "Executive Suite Rental Agency",
  "Mailbox Rental Service",
  "Makerspace",
  "Office Accessories Wholesaler",
  "Office Equipment Rental",
  "Office Equipment Repair Service",
  "Office Equipment Supplier",
  "Office Furniture Store",
  "Office Refurbishment Service",
  "Office Space Rental Agency",
  "Office Supplies Store",
  "Office Supply Store",
  "Office Supply Wholesaler",
  "Retail Space Rental Agency",
  "Shopfitter",
  "Stationery Manufacturer",
  "Stationery Store",
  "Stationery Wholesaler",
  "Used Office Furniture Store",
  "Copy Shop",
  "Copying Supply Store",
  "Custom Label Printer",
  "Digital Printer",
  "Digital Printing Service",
  "Graphic Designer",
  "Greeting Card Shop",
  "Lamination Service",
  "Print Shop",
  "Printer and Scanner Store",
  "Printer Ink Refill Store",
  "Printer Repair Service",
  "Printing Equipment and Supplies",
  "Printing Equipment Supplier",
  "Prints and Signs Store",
  "Rubber Stamp Store",
  "Screen Printer",
  "Screen Printing Shop",
  "Screen Printing Supply Store",
  "Seal Shop",
  "Sign Shop",
  "Sticker Manufacturer",
  "Toner Cartridge Supplier",
  "Design Agency",
  "Industrial Design Company",
  "Laboratory",
  "Market Researcher",
  "Patent Attorney",
  "Patent Office",
  "Research and Product Development",
  "Advertising Agency",
  "Advertising Photographer",
  "Affiliate Marketing Service",
  "Banner Store",
  "Business Development Service",
  "Call Center",
  "CRM Provider",
  "Desktop Publishing Service",
  "Direct Mail Advertising",
  "Internet Marketing Service",
  "Marketing Agency",
  "Marketing Consultant",
  "Media Consultant",
  "Meeting Planning Service",
  "Online Marketing Agency",
  "Promotional Item Store",
  "Promotional Products Supplier",
  "SEO Service",
  "Telemarketing Service",
  "Circular Distribution Service",
  "Container Service",
  "Container Supplier",
  "Container Terminal",
  "Courier and Delivery Service",
  "Courier Service",
  "Delivery Service",
  "Freight Forwarding Service",
  "Logistics Service",
  "Package locker",
  "Packaging Company",
  "Packaging Machinery",
  "Packaging Store",
  "Packaging Supply Store",
  "Refrigerated Transport Service",
  "River Port",
  "Shipping and Mailing Service",
  "Shipping Company",
  "Shipping Equipment Industry",
  "Shipping Service",
  "Vehicle Shipping Agent",
  "Warehouse",
  "Bar Stool Supplier",
  "Battery Wholesaler",
  "Cash and Carry Wholesaler",
  "Chemical Wholesaler",
  "Clothing Wholesale Market Place",
  "Clothing Wholesaler",
  "Coat Wholesaler",
  "Computer Wholesaler",
  "Construction Material Wholesaler",
  "Electrical Appliance Wholesaler",
  "Electrical Wholesaler",
  "Electronics Accessories Wholesaler",
  "Electronics Wholesaler",
  "Flow Control Product Wholesaler",
  "FMCG Goods Wholesaler",
  "Footwear Wholesaler",
  "Furniture Wholesaler",
  "Glassware Wholesaler",
  "Household Goods Wholesaler",
  "Industrial Chemicals Wholesaler",
  "Lighting Wholesaler",
  "Lingerie Wholesaler",
  "Luggage Wholesaler",
  "Natural Stone Wholesaler",
  "Novelties Wholesaler",
  "Oil Wholesaler",
  "Plastic Bags Wholesaler",
  "Plastic Wholesaler",
  "Rice Wholesaler",
  "Spices Wholesaler",
  "Sports Accessories Wholesaler",
  "Tool Wholesaler",
  "Valves and Actuators Wholesaler",
  "Wholesale Florist",
  "Wholesale Food Store",
  "Wholesale Grocer",
  "Wholesale Jeweler",
  "Wholesale Market",
  "Wholesaler",
  "Wholesaler Household Appliances",
  "Architect",
  "Architectural and Engineering Model Maker",
  "Architectural Designer",
  "Architecture Firm",
  "Biotechnology Engineer",
  "Blueprint Service",
  "Building Design Company",
  "Chemical Engineer",
  "Civil Engineer",
  "Civil Engineering Company",
  "Design Engineer",
  "Electrical Engineer",
  "Electronic Engineer",
  "Electronics Engineer",
  "Engineer",
  "Environmental Engineer",
  "Fabrication Engineer",
  "Gas Engineer",
  "Geotechnical Engineer",
  "Hydraulic Engineer",
  "Industrial Engineer",
  "Instrumentation Engineer",
  "Marine Engineer",
  "Mechanical Engineer",
  "Mining Engineer",
  "Nanotechnology Engineer",
  "Nuclear Engineer",
  "Petrochemical Engineer",
  "Precision Engineer",
  "Structural Engineer",
  "Telecommunications Engineer",
  "Textile Engineer",
  "Topography Company",
  "Aluminum Supplier",
  "Aluminum Window Manufacturer",
  "Asphalt Mixing Plant",
  "Bark Supplier",
  "Ceiling Supplier",
  "Cement Manufacturer",
  "Cement Supplier",
  "Concrete Contractor",
  "Concrete Metal Framework Supplier",
  "Concrete Product Supplier",
  "Copper Supplier",
  "Crushed Stone Supplier",
  "Dirt Supplier",
  "Door Supplier",
  "Dry Wall Supply Store",
  "Glass Block Supplier",
  "Glass Merchant",
  "Glass Shop",
  "Gold Mining Company",
  "Gravel Pit",
  "Gravel Plant",
  "Hay Supplier",
  "Insulation Materials Store",
  "Insulator Supplier",
  "Lumber Store",
  "Marble Supplier",
  "Masonry Supply Store",
  "Metal Supplier",
  "Mining Company",
  "Natural Stone Supplier",
  "Paving Materials Supplier",
  "Plast Window Store",
  "Plywood Supplier",
  "PVC Windows Supplier",
  "Quarry",
  "Ready Mix Concrete Supplier",
  "Roofing Supply Store",
  "Sand and Gravel Supplier",
  "Sand Plant",
  "Sod Supplier",
  "Steel Distributor",
  "Stone Supplier",
  "Turf Supplier",
  "Wax Supplier",
  "Window Supplier",
  "Wood Frame Supplier",
  "Wood Supplier",
  "Woodworker",
  "Woodworking Supply Store",
  "Acrylic Store",
  "Biochemical Supplier",
  "Biochemistry Lab",
  "Biotechnology Company",
  "Chemical Plant",
  "Chemistry Lab",
  "Kerosene Supplier",
  "Plastic Fabrication Company",
  "Plastic Injection Molding Service",
  "Propane Supplier",
  "PVC Industry",
  "Building Restoration Service",
  "Construction Machine Rental Service",
  "Crane Rental Agency",
  "Crane Service",
  "Engraver",
  "Glass Cutting Service",
  "Line Marking Service",
  "Monument Maker",
  "Road Construction Machine Repair Service",
  "Scaffolder",
  "Scaffolding Rental Service",
  "Stone Carving",
  "Stone Cutter",
  "Stonemason",
  "Window Installation Service",
  "Window Tinting Service",
  "Wood Floor Installation Service",
  "Acoustical Consultant",
  "Air Conditioning Contractor",
  "Asphalt Contractor",
  "Building Consultant",
  "Building Firm",
  "Building Inspector",
  "Chartered Surveyor",
  "Conservatory Construction Contractor",
  "Construction and Maintenance Office",
  "Construction Company",
  "Contractor",
  "Custom Home Builder",
  "Demolition Contractor",
  "Dock Builder",
  "Drilling Contractor",
  "Dry Wall Contractor",
  "Engineering Consultant",
  "Excavating Contractor",
  "Fence Contractor",
  "Fountain Contractor",
  "Garage Builder",
  "General Contractor",
  "Heating Contractor",
  "Height Works",
  "Home Builder",
  "Housing Development",
  "HVAC Contractor",
  "Industrial Consultant",
  "Insulation Contractor",
  "Interior Construction Contractor",
  "Interior Fitting Contractor",
  "Iron Steel Contractor",
  "Joiner",
  "Land Planning Authority",
  "Land Surveyor",
  "Lawn Sprinkler System Contractor",
  "Lighting Contractor",
  "Log Home Builder",
  "Logging Contractor",
  "Marble Contractor",
  "Marine Surveyor",
  "Masonry Contractor",
  "Mausoleum Builder",
  "Mechanical Contractor",
  "Modular Home Builder",
  "Paving Contractor",
  "Plasterer",
  "Pond Contractor",
  "Prefabricated House Companies",
  "Property Maintenance",
  "Quantity Surveyor",
  "Railing Contractor",
  "Railroad Contractor",
  "Railroad Ties Supplier",
  "Real Estate Surveyor",
  "Road Construction Company",
  "Roofing Contractor",
  "Shed Builder",
  "Sheet Metal Contractor",
  "Ship Building",
  "Siding Contractor",
  "Skylight Contractor",
  "Solar Energy Contractor",
  "Stair Contractor",
  "Steel Framework Contractor",
  "Stucco Contractor",
  "Sunroom Contractor",
  "Surveyor",
  "Swimming Pool Contractor",
  "Tennis Court Construction Company",
  "Tile Contractor",
  "Trade Fair Construction Company",
  "Well Drilling Contractor",
  "Wind Turbine Builder",
  "Commercial Refrigeration",
  "Commercial Refrigerator Supplier",
  "Dynamometer Supplier",
  "Electrical Equipment Supplier",
  "Factory Equipment Supplier",
  "Fiber-Optic Products Supplier",
  "Hydraulic Equipment Supplier",
  "Hydroponics Equipment Supplier",
  "Industrial Door Supplier",
  "Industrial Equipment Supplier",
  "Industrial Vacuum Equipment Supplier",
  "Laboratory Equipment Supplier",
  "Laminating Equipment Supplier",
  "Laser Equipment Supplier",
  "Machine Construction",
  "Machine Knife Supplier",
  "Mailing Machine Supplier",
  "Measuring Instruments Supplier",
  "Pump Supplier",
  "Scale Supplier",
  "Semi Conductor Supplier",
  "Stage Lighting Equipment Supplier",
  "Vending Machine Supplier",
  "Water Cooler Supplier",
  "Water Pump Supplier",
  "Water Treatment Supplier",
  "X-ray Equipment Supplier",
  "Awning Supplier",
  "Carport and Pergola Builder",
  "Deck Builder",
  "Earthworks Company",
  "Gazebo Builder",
  "Golf Course Builder",
  "Land Allotment",
  "Landscape Architect",
  "Landscape Designer",
  "Landscape Lighting Designer",
  "Landscaper",
  "Landscaping Service",
  "Landscaping Supply Store",
  "Pile Driver",
  "Rainwater Tank Supplier",
  "Retaining Wall Supplier",
  "Swimming Pool Supply Store",
  "Topsoil Supplier",
  "Water Works Equipment Supplier",
  "Abrasives Supplier",
  "Aggregate Supplier",
  "Air Compressor Supplier",
  "Air Filter Supplier",
  "Alternator Supplier",
  "Aluminum Frames Supplier",
  "Antenna Service",
  "Barrel Supplier",
  "Bearing Supplier",
  "Butane Gas Supplier",
  "Cotton Supplier",
  "Decal Supplier",
  "Dry Ice Supplier",
  "Dyeworks",
  "Electric Motor Repair Shop",
  "Electrical Supply Store",
  "Fastener Supplier",
  "Fiberglass Supplier",
  "Filtration Plant",
  "Finishing Materials Supplier",
  "Fire Department Equipment Supplier",
  "Fire Protection System Supplier",
  "Foam Rubber Producer",
  "Foam Rubber Supplier",
  "Gas Cylinders Supplier",
  "Gas Logs Supplier",
  "Generator Shop",
  "Gypsum Product Supplier",
  "Heating Equipment Supplier",
  "Heating Oil Supplier",
  "Helium Gas Supplier",
  "Hot Water System Supplier",
  "Industrial Framework Supplier",
  "Industrial Gas Supplier",
  "Industrial Supermarket",
  "Jewelry Equipment Supplier",
  "Marine Supply Store",
  "Metal Industry Suppliers",
  "Metal Machinery Supplier",
  "Oil Field Equipment Supplier",
  "Pallet Supplier",
  "Paper Bag Supplier",
  "Paper Shredding Machine Supplier",
  "Plastic Bag Supplier",
  "Plastic Products Supplier",
  "Polymer Supplier",
  "Polythene and Plastic Sheeting Supplier",
  "Portable Toilet Supplier",
  "Power Plant Equipment Supplier",
  "Protective Clothing Supplier",
  "Rolled Metal Products Supplier",
  "Rubber Products Supplier",
  "Satellite Communication Service",
  "Scientific Equipment Supplier",
  "Solar Hot Water System Supplier",
  "Steel Drum Supplier",
  "Tool and Die Shop",
  "Used Store Fixture Supplier",
  "Water Filter Supplier",
  "Water Softening Equipment Supplier",
  "Welding Gas Supplier",
  "Welding Supply Store",
  "Agricultural Machinery Manufacturer",
  "Aircraft Manufacturer",
  "Aluminum Welder",
  "Anodizer",
  "Artificial Plant Supplier",
  "Battery Manufacturer",
  "Blacksmith",
  "Brick Manufacturer",
  "Ceramic Manufacturer",
  "Chemical Manufacturer",
  "Clothes and Fabric Manufacturer",
  "Concrete Factory",
  "Coppersmith",
  "Cotton Mill",
  "Desalination Plant",
  "Display Stand Manufacturer",
  "Electric Utility Manufacturer",
  "Electronics Manufacturer",
  "Elevator Manufacturer",
  "Fabric Product Manufacturer",
  "Feed Manufacturer",
  "Fireplace Manufacturer",
  "FMCG Manufacturer",
  "Foundry",
  "Fur Manufacturer",
  "Gasket Manufacturer",
  "Glass Blower",
  "Glass Industry",
  "Glass Manufacturer",
  "Glassware Manufacturer",
  "Goldsmith",
  "Industrial Area",
  "Industrial Real Estate Agency",
  "Iron Works",
  "Jute Mill",
  "Knitwear Manufacturer",
  "Lighting Manufacturer",
  "Machine Workshop",
  "Machinery Parts Manufacturer",
  "Machining Manufacturer",
  "Manufactured Home Transporter",
  "Manufacturer",
  "Match Box Manufacturer",
  "Mechanical Plant",
  "Metal Construction Company",
  "Metal Fabricator",
  "Metal Finisher",
  "Metal Polishing Service",
  "Metal Processing Company",
  "Metallurgy Company",
  "Microbiologist",
  "Millwork Shop",
  "Mining Consultant",
  "Mold Maker",
  "Optical Products Manufacturer",
  "Paint Manufacturer",
  "Paper Mill",
  "Plant and Machinery Hire",
  "Plastic Resin Manufacturer",
  "Portable Building Manufacturer",
  "Saw Mill",
  "Scrap Metal Dealer",
  "Silversmith",
  "Souvenir Manufacturer",
  "Stainless Steel Plant",
  "Steel Construction Company",
  "Steel Erector",
  "Steel Fabricator",
  "Steelwork Design Company",
  "Steelwork Manufacturer",
  "Stove Builder",
  "Tannery",
  "Textile Mill",
  "Tile Manufacturer",
  "Tool Manufacturer",
  "Trailer Manufacturer",
  "Truss Manufacturer",
  "Ventilating Equipment Manufacturer",
  "Weaving Mill",
  "Welder",
  "Air Compressor Repair Service",
  "Airbrushing Service",
  "Cooling Plant",
  "Diesel Engine Repair Service",
  "Drafting Service",
  "Equipment Rental Agency",
  "Forklift Rental Service",
  "Grain Elevator",
  "Hydraulic Repair Service",
  "Machine Maintenance",
  "Machine Repair Service",
  "Machine Shop",
  "Manufacturing Service",
  "Mercantile Development",
  "Metal Heat Treating Service",
  "Metal Stamping Service",
  "Molding Supplier",
  "Polygraph Service",
  "Powder Coating Service",
  "Pumping Equipment and Service",
  "Saw Sharpening Service",
  "Sharpening Service",
  "Shredding Service",
  "Stall Installation Service",
  "Tool Grinding Service",
  "Water Jet Cutting Service",
  "Building Equipment Hire Service",
  "Building Materials Market",
  "Building Materials Store",
  "Building Materials Supplier",
  "Coin Operated Laundry Equipment Supplier",
  "Construction Equipment Supplier",
  "Construction Machine Dealer",
  "Construction Machinery and Equipment Store",
  "Crane Dealer",
  "Drafting Equipment Supplier",
  "Drilling Equipment Supplier",
  "Equipment Supplier",
  "Fire Protection Equipment Supplier",
  "Hose Supplier",
  "Irrigation Equipment Supplier",
  "Janitorial Equipment Supplier",
  "Ladder Supplier",
  "Material Handling Equipment Supplier",
  "Metal Detecting Equipment Supplier",
  "Mining Equipment",
  "Oxygen Equipment Supplier",
  "Pipe Supplier",
  "Playground Equipment Supplier",
  "Plumbing Supply Store",
  "Pneumatic Tools Supplier",
  "Railroad Equipment Supplier",
  "Safety and Work Wear Store",
  "Safety Equipment Supplier",
  "Screw Supplier",
  "Spring Supplier",
  "Tool Rental Service",
  "Tool Repair Shop",
  "Tool Store",
  "Toolroom",
  "Architecture School",
  "Auditorium",
  "Business School",
  "Chemistry Faculty",
  "Christian College",
  "College",
  "College of Agriculture",
  "Community College",
  "Dental School",
  "Engineering School",
  "Faculty of Arts",
  "Faculty of Law",
  "Faculty of Pharmacy",
  "Faculty of Psychology",
  "Faculty of Science",
  "Faculty of Sports",
  "Geography and History Faculty",
  "Government College",
  "Graduate School",
  "Institute of Geography and Statistics",
  "Institute of Technology",
  "Junior College",
  "Law School",
  "Management School",
  "Media and Information Sciences Faculty",
  "Medical School",
  "Open University",
  "Polytechnic School",
  "Private College",
  "Private University",
  "Public University",
  "Research Engineer",
  "Research Foundation",
  "Research Institute",
  "Residential College",
  "Science Academy",
  "Sixth Form College",
  "Student Union",
  "Teacher College",
  "Technical University",
  "University",
  "University Department",
  "University Library",
  "Vocational College",
  "Women's College",
  "Acupuncture School",
  "Aromatherapy Class",
  "Class",
  "Computer Training School",
  "Cooking Class",
  "Cooking School",
  "Culinary School",
  "Drawing Lessons",
  "Pottery Classes",
  "Self-Defense School",
  "Shogi Lesson",
  "Software Training Institute",
  "Wood Working Class",
  "Board of Education",
  "Career and Education Provider",
  "Career Coach",
  "Civil Examinations Academy",
  "Education Center",
  "Educational Institution",
  "Educational Supply Store",
  "Educational Testing Service",
  "Foreign Exchange Students Organization",
  "Life Coach",
  "Private Tutor",
  "Resume Service",
  "School Supply Store",
  "Student Career Counseling Office",
  "Student Dormitory",
  "Student Housing Center",
  "Studying Center",
  "Chinese Language Instructor",
  "Chinese Language School",
  "English Language Camp",
  "English Language Instructor",
  "English Language School",
  "Foreign Languages Program School",
  "French Language School",
  "German Language Instructor",
  "German Language School",
  "Grammar School",
  "Japanese Language Instructor",
  "Language Course Provider",
  "Language School",
  "Telecommunication School",
  "Conservatory of Music",
  "Drama School",
  "Drum School",
  "Guitar Instructor",
  "Music College",
  "Music Conservatory",
  "Music School",
  "Agricultural High School",
  "All-Boys High School",
  "All-Girls High School",
  "Bilingual School",
  "Boarding School",
  "Catholic School",
  "CBSE School",
  "Charter School",
  "Coed School",
  "Community School",
  "Day Care Center",
  "Elementary School",
  "Folk High School",
  "Government School",
  "Gymnasium CZ",
  "Gymnasium School",
  "Head Start Center",
  "High School",
  "Higher Secondary School",
  "Hospitality High School",
  "International School",
  "Lyceum",
  "Middle School",
  "Play School",
  "Pre-Gymnasium School",
  "Preparatory School",
  "Preschool",
  "Preschool Program Institution",
  "Primary School",
  "Private School",
  "Public School",
  "School",
  "School Administrator",
  "School Center",
  "School District Office",
  "School House",
  "Secondary School Three",
  "Single Sex Secondary School",
  "Waldorf School",
  "Adult Education School",
  "After School Program",
  "Blind School",
  "Cram School",
  "Deaf School",
  "Distance Learning Center",
  "Drivers License Training School",
  "Driving School",
  "Driving Test Centre",
  "Evening School",
  "Fire Fighters Academy",
  "Firearms Academy",
  "ICSE School",
  "Learner Driver Training Area",
  "Learning Center",
  "Mathematics School",
  "Military School",
  "Montessori School",
  "Parochial School",
  "Photography Class",
  "Police Academy",
  "Religious School",
  "School For The Deaf",
  "Senior High School",
  "Special Education School",
  "Study at Home School",
  "Accounting School",
  "Apprenticeship Center",
  "Art School",
  "Barber School",
  "Bartending School",
  "Beauty School",
  "Design Institute",
  "Emergency Training School",
  "Farm School",
  "Fashion Design School",
  "Flight School",
  "Hardware Training Institute",
  "Hospitality and Tourism School",
  "Hotel Management School",
  "Insurance School",
  "Massage School",
  "Modeling School",
  "Nursery School",
  "Nursing School",
  "Photography School",
  "Real Estate School",
  "Sailing School",
  "Seminary",
  "Technical School",
  "Trade School",
  "Training School",
  "Vocational School",
  "Vocational School One",
  "Appliance Parts Supplier",
  "Appliance Store",
  "Battery Store",
  "Cable Company",
  "Electronic Parts Supplier",
  "Electronic Spare Parts and Components Store",
  "Electronics Company",
  "Electronics Hire Shop",
  "Electronics Store",
  "Electronics Vending Machine",
  "Typewriter Supplier",
  "Used Appliance Store",
  "Vacuum Cleaner Store",
  "Vacuum Cleaning System Supplier",
  "Washer and Dryer Store",
  "Audio Visual Equipment Rental Service",
  "Binoculars Store",
  "Camera Store",
  "Closed Circuit Television Store",
  "Hi-fi shop",
  "Home Audio Store",
  "Home Theater Store",
  "Photo Lab",
  "Photo Restoration Service",
  "Photo Shop",
  "Screen Store",
  "Stereo Rental Store",
  "Telescope Store",
  "TV store",
  "Call Shop",
  "Cell Phone Accessory Store",
  "Cell Phone Store",
  "Computer Accessories Store",
  "Computer and Accessories Store",
  "Computer Desk Store",
  "Computer Hardware Manufacturer",
  "Computer Networking Center",
  "Computer Service",
  "Computer Store",
  "Telecommunications Equipment Supplier",
  "Telecommunications Service Provider",
  "Telephone Answering Service",
  "Telephone Company",
  "Telephone Exchange",
  "Used Computer Store",
  "Computer Software Store",
  "DNS Provider",
  "Email Service Provider",
  "Internet Provider",
  "Internet Service Provider",
  "Internet Shop",
  "IUP",
  "Mobile Network Operator",
  "Phone and Internet Service",
  "Process Server",
  "Search Engine Company",
  "Software Company",
  "Software Vendor",
  "Telecommunications Contractor",
  "VPN Service",
  "Web Collaboration Platform",
  "Web Hosting Company",
  "Wi-Fi Spot",
  "Appliance Rental Service",
  "Appliance Repair Service",
  "Appliances Customer Service",
  "Audio Visual Equipment Repair Service",
  "Camera Repair Shop",
  "Cell phone charging station",
  "Cell Phone Recycling and Unlocking Service",
  "Cell Phone Unlocking Service",
  "Computer Repair Service",
  "Computer Support and Service Company",
  "Electrical Repair Shop",
  "Electronics Repair Shop",
  "Furnace Repair Service",
  "Microwave Oven Repair Service",
  "Mobile Phone Repair Shop",
  "Phone Repair Service",
  "Refrigerator Repair Service",
  "Small Appliance Repair Service",
  "Technical Service",
  "Television Repair Service",
  "Typewriter Repair Service",
  "Vacuum Cleaner Repair Shop",
  "Video Camera Repair Service",
  "Video Equipment Repair Service",
  "Washer and Dryer Repair Service",
  "Adult Dating Service",
  "Adult DVD Store",
  "Adult Entertainment Club",
  "Adult Entertainment Store",
  "Airsoft Supply Store",
  "Dating Service",
  "Dude Ranch",
  "Erotic Clothing Store",
  "Erotic Massage",
  "Gay Sauna",
  "Gun Club",
  "Gun Shop",
  "Host Club",
  "Nudist Club",
  "Nudist Park",
  "Sex Toy Store",
  "Baby Swimming School",
  "Boot Camp Center",
  "Children's Amusement Center",
  "Children's Cafe",
  "Children's Club",
  "Children's Farm",
  "Children's Library",
  "Children's Party Buffet",
  "Children's Party Service",
  "Children's Store",
  "Children's Theater",
  "Children's Toys Store",
  "Children Hall",
  "Indoor Playground",
  "Indoor Snowcenter",
  "Indoor Swimming Pool",
  "Playground",
  "Soapland",
  "Theme Park",
  "Toy and Game Manufacturer",
  "Toy Library",
  "Toy Manufacturer",
  "Toy Store",
  "Water Park",
  "Youth Center",
  "Youth Club",
  "Youth Group",
  "Blues Club",
  "Cabaret Club",
  "Club",
  "Comedy Club",
  "Country Club",
  "Dart Bar",
  "Disco Club",
  "Gay Bar",
  "Gay Night Club",
  "Girl Bar",
  "Jazz Club",
  "Karaoke",
  "Karaoke Equipment Rental Service",
  "Mobile Disco",
  "Night Club",
  "Amusement Center",
  "Amusement Machine Supplier",
  "Amusement Park",
  "Amusement Park Ride",
  "Amusement Ride Supplier",
  "Aquatic Centre",
  "Arena",
  "Barbecue area",
  "BBQ Area",
  "Bungee Jumping Center",
  "Carnival Club",
  "Circus",
  "Comic Cafe",
  "Cosplay Cafe",
  "Entertainer",
  "Entertainment Agency",
  "Escape Room Center",
  "Event Management Company",
  "Event Planner",
  "Event Technology Service",
  "Event Ticket Seller",
  "Event Venue",
  "Fairground",
  "Ferris wheel",
  "Festival",
  "Festival Hall",
  "Fortune Telling Service",
  "Ghost Town",
  "Greyhound Stadium",
  "Haunted House",
  "High Ropes Course",
  "Internet Cafe",
  "Laser Tag Center",
  "Lido",
  "Outdoor Bath",
  "Public Swimming Pool",
  "Reenactment Site",
  "Roller Coaster",
  "Sambodrome",
  "Stadium",
  "Stage",
  "Village Hall",
  "Betting Agency",
  "Bookmaker",
  "Casino",
  "Gambling House",
  "Gambling Instructor",
  "Gambling Service",
  "Lottery Retailer",
  "Lottery Shop",
  "Lottery Vendor",
  "Off-Track Betting Shop",
  "Online Casino or Bookmaker",
  "Online Lottery Ticket Vendor",
  "Online Sports Betting Vendor",
  "Scratch Card Vendor",
  "Bingo Hall",
  "Board Game Club",
  "Bridge",
  "Bridge Club",
  "Chess and Card Club",
  "Chess Club",
  "Chess Instructor",
  "Game Store",
  "Gaming service Provider",
  "Mah Jong House",
  "Pachinko Parlor",
  "Pinball Machine Supplier",
  "Used Game Store",
  "Video Arcade",
  "Video Game Rental Kiosk",
  "Video Game Rental Service",
  "Video Game Rental Store",
  "Video Game Store",
  "Aboriginal Art Gallery",
  "Arboretum",
  "Archaeological Museum",
  "Army Museum",
  "Art Cafe",
  "Art Center",
  "Art Gallery",
  "Art Museum",
  "Aviation Museum",
  "Castle",
  "Children's Museum",
  "Cultural Center",
  "Ethnographic Museum",
  "Exhibit",
  "Exhibition and Trade Centre",
  "Exhibition Planner",
  "Film and Photograph Library",
  "Fortress",
  "Gallery",
  "Handicraft Museum",
  "Heritage Building",
  "Heritage Museum",
  "Heritage Preservation",
  "Historical Place Museum",
  "History Museum",
  "Local History Museum",
  "Maritime Museum",
  "Modern Art Museum",
  "Museum",
  "Museum of Space History",
  "Museum of Zoology",
  "National Library",
  "National Museum",
  "Natural History Museum",
  "Observatory",
  "Open Air Museum",
  "Planetarium",
  "Rail Museum",
  "Science Museum",
  "Sculpture Museum",
  "Technology Museum",
  "Technology Park",
  "Toy Museum",
  "Visitor Center",
  "War Museum",
  "Water Mill",
  "Wax Museum",
  "DJ Service",
  "DJ Supply Store",
  "Drive-In Movie Theater",
  "IMAX Theater",
  "Live Music Venue",
  "Movie Rental Kiosk",
  "Movie Rental Store",
  "Movie Streaming Service",
  "Movie Theater",
  "Musical Club",
  "Outdoor movie theater",
  "Video Karaoke",
  "Video Store",
  "Amateur Theater",
  "Amphitheater",
  "Ballet Theater",
  "Concert Hall",
  "Dinner Theater",
  "Drama Theater",
  "Flamenco Theater",
  "Opera Company",
  "Opera House",
  "Performing Arts Group",
  "Performing Arts Theater",
  "Philharmonic Hall",
  "Puppet Theater",
  "Theater Company",
  "Theater Production",
  "Theater Supply Store",
  "Balloon Artist",
  "Balloon Store",
  "Banquet Hall",
  "Bouncy Castle Hire",
  "Fireworks Store",
  "Fireworks Supplier",
  "Gift Basket Store",
  "Gift Shop",
  "Gift Wrap Store",
  "Invitation Printing Service",
  "Marquee Hire Service",
  "Marriage Celebrant",
  "New Years Tree Market",
  "Party Equipment Rental Service",
  "Party Planner",
  "Party Store",
  "Singing Telegram Service",
  "Tent Rental Service",
  "Wedding Bakery",
  "Wedding Buffet",
  "Wedding Chapel",
  "Wedding Photographer",
  "Wedding Planner",
  "Wedding Service",
  "Wedding Souvenir Shop",
  "Wedding Store",
  "Wedding Venue",
  "Agriculture & Produce",
  "Asian Grocery Stores",
  "Bakery & Pastry",
  "Beer & Wine",
  "Beverages & Liquor",
  "Candy & Chocolate",
  "Coffee & Tea",
  "Food Production",
  "Fruits & Vegetables",
  "Grocery Stores & Markets",
  "Lunch & Catering",
  "Meat",
  "Smoking & Tobacco",
  "Acupuncture Clinic",
  "Alternative Medicine Practitioner",
  "Chinese Medicine Clinic",
  "Diabetes Center",
  "Free Clinic",
  "Holistic Medicine Practitioner",
  "Internal Medicine Ward",
  "Medical Clinic",
  "Ophthalmology Clinic",
  "Oriental Medicine Clinic",
  "Orthopedic Clinic",
  "Otolaryngology Clinic",
  "Pain Control Clinic",
  "Physical Examination Center",
  "Physical Therapy Clinic",
  "Psychoneurological Specialized Clinic",
  "Seitai",
  "Specialized Clinic",
  "STD Clinic",
  "TB Clinic",
  "Travel Clinic",
  "Walk-In Clinic",
  "Women's Health Clinic",
  "Cosmetic Dentist",
  "Dental Clinic",
  "Dental Hygienist",
  "Dental Implants Periodontist",
  "Dental Laboratory",
  "Dental Radiology",
  "Dental Supply Store",
  "Dentist",
  "Denture Care Center",
  "Emergency Dental Service",
  "Teeth Whitening Service",
  "Cancer Treatment Center",
  "Diagnostic Center",
  "Dialysis Center",
  "Drug Testing Service",
  "HIV Testing Center",
  "Hygiene Service",
  "Hygiene Station",
  "Mammography Service",
  "Medical Diagnostic Imaging Center",
  "Medical Laboratory",
  "MFR",
  "MRI Center",
  "STD Testing Service",
  "X-ray Lab",
  "Doctor",
  "Gastrointestinal Surgeon",
  "General Practitioner",
  "Hand Surgeon",
  "LASIK Surgeon",
  "Neurosurgeon",
  "Oral Surgeon",
  "Orthopedic Surgeon",
  "Physiatrist",
  "Physician Referral Service",
  "Plastic Surgeon",
  "Plastic Surgery Clinic",
  "Surgeon",
  "Surgical Center",
  "Surgical Products Wholesaler",
  "Surgical Supply Store",
  "Vascular Surgeon",
  "Diabetes Equipment Supplier",
  "Hospital Equipment and Supplies Store",
  "Hygiene Articles Wholesaler",
  "Medical Billing Service",
  "Medical Certificate Service",
  "Medical Equipment Manufacturer",
  "Medical Equipment Supplier",
  "Medical Supply Store",
  "Medical Technology Manufacturer",
  "Medical Transcription Service",
  "Sanitation Service",
  "Ambulance Service",
  "Blood Bank",
  "Blood Donation Center",
  "Blood Testing Service",
  "Community Health Centre",
  "Emergency Call Booth",
  "Emergency Care Physician",
  "Emergency Care Service",
  "Emergency Room",
  "First Aid Station",
  "General Hospital",
  "Government Hospital",
  "Health Consultant",
  "Health Resort",
  "Heart Hospital",
  "Home Health Care Service",
  "Hospital",
  "Hospital Department",
  "Local Medical Service",
  "Maternity Hospital",
  "Medical Center",
  "Military Hospital",
  "National Health Foundation",
  "Occupational Health Service",
  "Occupational Safety and Health",
  "Organ Donation and Tissue Bank",
  "Private Hospital",
  "Public Medical Center",
  "Retreat Center",
  "Self-Service Health Station",
  "Specialized Hospital",
  "University Hospital",
  "Urgent Care Center",
  "Veterans Hospital",
  "Acupuncturist",
  "Allergist",
  "Anesthesiologist",
  "Audiologist",
  "Bonesetter",
  "Cardiologist",
  "Chiropractor",
  "Dermatologist",
  "Diabetologist",
  "Endocrinologist",
  "Endodontist",
  "Endoscopist",
  "Gastroenterologist",
  "Hematologist",
  "Immunologist",
  "Infectious Disease Physician",
  "Internist",
  "Kinesiologist",
  "Medical Examiner",
  "Medical Group",
  "Medical Office",
  "Medical Spa",
  "Neonatal Physician",
  "Nephrologist",
  "Neurologist",
  "Nutritionist",
  "Obstetrician-Gynecologist",
  "Occupational Medical Physician",
  "Oncologist",
  "Ophthalmologist",
  "Optometrist",
  "Orthodontist",
  "Orthoptist",
  "Osteopath",
  "Otolaryngologist",
  "Pain Management Physician",
  "Pathologist",
  "Pediatric Ophthalmologist",
  "Pediatrician",
  "Periodontist",
  "Podiatrist",
  "Proctologist",
  "Prosthodontist",
  "Pulmonologist",
  "Radiologist",
  "Reflexologist",
  "Registered General Nurse",
  "Rheumatologist",
  "Speech Pathologist",
  "Sports Medicine Clinic",
  "Sports Medicine Physician",
  "Urologist",
  "Urology Clinic",
  "Venereologist",
  "Addiction Treatment Center",
  "Alcoholism Treatment Program",
  "Child Psychologist",
  "Domestic Abuse Treatment Center",
  "Eating Disorder Treatment Center",
  "Halfway House",
  "Helpline",
  "Mental Health Clinic",
  "Mental Health Service",
  "Psychiatric Hospital",
  "Psychiatrist",
  "Psychoanalyst",
  "Psychologist",
  "Psychopedagogy Clinic",
  "Psychosomatic Medical Practitioner",
  "Psychotherapist",
  "Rehabilitation Center",
  "Chinese Medicine Store",
  "Drug Store",
  "Herbal Medicine Store",
  "Homeopath",
  "Homeopathic Pharmacy",
  "Medicine Exporter",
  "Online Pharmacy",
  "Online Prescription Medication Vendor",
  "Oriental Medicine Store",
  "Pharmaceutical Company",
  "Pharmaceutical Lab",
  "Pharmaceutical Products Wholesaler",
  "Pharmacy",
  "Veterinary Pharmacy",
  "Wholesale Drugstore",
  "Disability Equipment Supplier",
  "Disability Services and Support Organisation",
  "Mobility Equipment Supplier",
  "Orthopedic Shoe Store",
  "Orthotics & Prosthetics Service",
  "Physiotherapy Equipment Supplier",
  "Prosthetics",
  "Wheelchair Rental Service",
  "Wheelchair Store",
  "Abortion Clinic",
  "Adoption Agency",
  "Assistante Maternelle",
  "Birth Center",
  "Birth Certificate Service",
  "Birth Control Center",
  "Child Health Care Center",
  "Childbirth Class",
  "Children's Hospital",
  "Children Policlinic",
  "Family Counselor",
  "Family Day Care Service",
  "Family Planning Center",
  "Family Planning Counselor",
  "Family Practice Physician",
  "Family Service Center",
  "Fertility Clinic",
  "Fertility Physician",
  "Foster Care Service",
  "Marriage Counselor",
  "Midwife",
  "Paternity Testing Service",
  "Pediatric Cardiologist",
  "Pediatric Dentist",
  "Perinatal Center",
  "Pregnancy Care Center",
  "Reproductive Health Clinic",
  "Sperm Bank",
  "Youth Care",
  "Adult Day Care Center",
  "Adult Foster Care Service",
  "Aromatherapy Service",
  "Asian Massage Therapist",
  "Assisted Living Facility",
  "Biofeedback Therapist",
  "Craniosacral Therapy",
  "Drug Addiction Treatment Center",
  "Home Help Service",
  "Home Help Service Agency",
  "Hospice",
  "Hypnotherapy Service",
  "Lymph Drainage Therapist",
  "Nursing Agency",
  "Nursing Home",
  "Occupational Therapist",
  "Physical Therapist",
  "Reiki Therapist",
  "Sexologist",
  "Sports Massage Therapist",
  "Thai Massage Therapist",
  "Contact Lenses Supplier",
  "Deaf Service",
  "Eye Care Center",
  "Glasses Store",
  "Hearing Aid Repair Service",
  "Hearing Aid Store",
  "Optical Wholesaler",
  "Optician",
  "Art & Antiques",
  "Art Dealer",
  "Art Handcraft",
  "Art Restoration Service",
  "Art Studio",
  "Art Supply Store",
  "Artist",
  "Chamber of Handicrafts",
  "Craft Store",
  "Dye Store",
  "Handicraft",
  "Handicraft Exporter",
  "Handicraft Fair",
  "Handicraft School",
  "Handicrafts Wholesaler",
  "Idol Manufacturer",
  "Laser Cutting Service",
  "Societe de Flocage",
  "Astrologer",
  "Gemologist",
  "Metaphysical Supply Store",
  "Naturopathic Practitioner",
  "Numerologist",
  "Psychic",
  "Ammunition Supplier",
  "Bait Shop",
  "Fishing Camp",
  "Fishing Charter",
  "Fishing Club",
  "Fishing Pier",
  "Fishing Pond",
  "Fishing Store",
  "Hunting and Fishing Store",
  "Hunting Area",
  "Hunting Club",
  "Hunting Preserve",
  "Hunting Store",
  "Prawn Fishing",
  "Taxidermist",
  "Aeromodel Shop",
  "Anime Club",
  "Coin Dealer",
  "Collectibles Store",
  "Computer Club",
  "Doll Restoration Service",
  "Doll Store",
  "Figurine Shop",
  "Historical Society",
  "Hobby Store",
  "Leisure Centre",
  "Magic Store",
  "Magician",
  "Model Car Play Area",
  "Model Design Company",
  "Model Shop",
  "Model Train Store",
  "Monogramming Service",
  "Playgroup",
  "Scale Model Club",
  "Scale Repair Service",
  "Stamp Collectors Club",
  "Summer Toboggan Run",
  "Trading Card Store",
  "Stone & Glass Work",
  "Band",
  "Choir",
  "Drum Store",
  "Guitar Store",
  "Music Instructor",
  "Musical Instrument Manufacturer",
  "Musical Instrument Rental Service",
  "Musical Instrument Repair Shop",
  "Musical Instrument Store",
  "Musician",
  "Orchestra",
  "Piano Instructor",
  "Piano Maker",
  "Piano Repair Service",
  "Piano Store",
  "Piano Tuning Service",
  "Rock Music Club",
  "Sheet Music Store",
  "Stringed instrument maker",
  "Used Musical Instrument Store",
  "Violin Shop",
  "Vocal Instructor",
  "Clothes and Fabric Wholesaler",
  "Embroidery Service",
  "Embroidery Shop",
  "Fabric Store",
  "Fabric Wholesaler",
  "Fashion Designer",
  "Haberdashery",
  "Knitting Instructor",
  "Leather Goods Manufacturer",
  "Needlework Shop",
  "Quilt Shop",
  "Sewing Company",
  "Sewing Machine Repair Service",
  "Sewing Machine Store",
  "Sewing Shop",
  "Stitching Class",
  "Thread Supplier",
  "Threads and Yarns Wholesaler",
  "Wool Store",
  "Yarn Store",
  "Beach Entertainment Shop",
  "Beach Pavillion",
  "Botanical Garden",
  "Camp",
  "Camp Site",
  "Campground",
  "Camping cabin",
  "Camping Farm",
  "Camping Store",
  "Canoeing Area",
  "Carriage Ride Service",
  "Country Park",
  "Diving Contractor",
  "Dogsled Ride Service",
  "Ecological Park",
  "Farmstay",
  "Hiking Area",
  "Historical Landmark",
  "National Forest",
  "National Park",
  "National Reserve",
  "Nature Preserve",
  "Observation Deck",
  "Off-Roading Area",
  "Outdoor Activity Organiser",
  "Outdoor Swimming Pool",
  "Pagoda",
  "Park",
  "Park and Ride",
  "Parkour Spot",
  "Picnic Ground",
  "Promenade",
  "Ranch",
  "Recreation Center",
  "RV Park",
  "Scenic Spot",
  "Scout Hall",
  "Scout Home",
  "Scouting",
  "Shelter",
  "State Park",
  "Summer Camp",
  "Airbrushing Supply Store",
  "Calligraphy Lesson",
  "Paint Store",
  "Painting",
  "Painting Lessons",
  "Painting Studio",
  "Paintings Store",
  "Paper Distributor",
  "Paper Exporter",
  "Pen Store",
  "Scrapbooking Store",
  "Bathroom Remodeler",
  "Bathroom Supply Store",
  "Countertop Store",
  "Cutlery Store",
  "Disposable Tableware Supplier",
  "Hot Tub Store",
  "Incense Supplier",
  "Ironware Dealer",
  "Kitchen Remodeler",
  "Kitchen Supply Store",
  "Knife Store",
  "Linens Store",
  "Metalware Dealer",
  "Metalware Producer",
  "Refrigerator Store",
  "Shower Door Shop",
  "African Goods Store",
  "Asian Household Goods Store",
  "Australian Goods Store",
  "Butsudan Store",
  "Christmas Store",
  "Feng Shui Shop",
  "Hawaiian Goods Store",
  "Irish Goods Store",
  "Native American Goods Store",
  "Oriental Rug Store",
  "Tatami Store",
  "Basket Supplier",
  "Bedding Store",
  "Blinds Shop",
  "Boiler and Heating Service",
  "Carpet Manufacturer",
  "Carpet Wholesaler",
  "Ceramics Wholesaler",
  "Christmas Tree Farm",
  "Curtain Store",
  "Curtain Supplier and Maker",
  "Decoration and Interior Design Store",
  "Display Home Centre",
  "Door Manufacturer",
  "Door Shop",
  "Door Warehouse",
  "Fireplace Store",
  "Interior Door",
  "Lamp Shade Supplier",
  "Mattress Store",
  "Mirror Shop",
  "Picture Frame Shop",
  "Poster Store",
  "Pottery Manufacturer",
  "Rug Store",
  "Sheepskin and Wool Products Supplier",
  "Tile Store",
  "Upholstery Shop",
  "Wallpaper Store",
  "Waterbed Store",
  "Willow Basket Manufacturer",
  "Air Conditioning Repair Service",
  "Air Conditioning Store",
  "Air Conditioning System Supplier",
  "Boiler Manufacturer",
  "Boiler Supplier",
  "Firewood Supplier",
  "Furnace Parts Supplier",
  "Furnace Store",
  "Gas Installation Service",
  "Gas Shop",
  "Radiator Shop",
  "Solar Energy Equipment Supplier",
  "Wood Stove Shop",
  "Carpet Store",
  "Leather Exporter",
  "Leather Goods Store",
  "Leather Goods Supplier",
  "Leather Goods Wholesaler",
  "Leather Wholesaler",
  "Map Store",
  "Paper Store",
  "Silk Store",
  "Stamp Shop",
  "Amish Furniture Store",
  "Antique Furniture Restoration Service",
  "Antique Furniture Store",
  "Bar Restaurant Furniture Store",
  "Bed Shop",
  "Bedroom Furniture Store",
  "Cabinet Maker",
  "Cabinet Store",
  "Cane Furniture Store",
  "Children's Furniture Store",
  "Fitted Furniture Supplier",
  "Flat Pack Assembly",
  "Furnished Apartment Building",
  "Furniture Accessories",
  "Furniture Accessories Supplier",
  "Furniture Manufacturer",
  "Furniture Rental Service",
  "Furniture Store",
  "Futon Store",
  "Garden Furniture Shop",
  "Kitchen Furniture Store",
  "Living Room Furniture Store",
  "Outdoor Furniture Store",
  "Pine Furniture Shop",
  "Rustic Furniture Store",
  "Shelving Store",
  "Shop Supermarket Furniture Store",
  "Sofa Store",
  "Unfinished Furniture Store",
  "Used Furniture Store",
  "Arborist and Tree Surgeon",
  "Bonsai Plant Supplier",
  "Conservatory Specialist",
  "Dried Flower Shop",
  "Fence Supply Store",
  "Flag Store",
  "Florist",
  "Flower Market",
  "Garden Building Supplier",
  "Garden Center",
  "Gardener",
  "Grill Store",
  "Lawn Equipment Rental Service",
  "Lawn Irrigation Equipment Supplier",
  "Lawn Mower Repair Service",
  "Lawn Mower Store",
  "Mulch Supplier",
  "Orchid Farm",
  "Patio Enclosure Supplier",
  "Plant Art Dealer",
  "Plant Display Store",
  "Pond Fish Supplier",
  "Pond Supply Store",
  "Pottery Store",
  "Rock Shop",
  "Seed Supplier",
  "Silk Plant Shop",
  "Swimming Pool Repair Service",
  "Tree Farm",
  "Tree Service",
  "Wholesale Plant Nursery",
  "Wicker Store",
  "Flower Delivery",
  "Flower Designer",
  "Furniture Maker",
  "Home Automation Company",
  "Interior Architect Office",
  "Interior Designer",
  "Interior Plant Service",
  "Junk Dealer",
  "Junkyard",
  "Orchid Grower",
  "Plant Nursery",
  "Antique Store",
  "Architectural Salvage Store",
  "Auction House",
  "Boutique",
  "Candle Store",
  "Chinaware Store",
  "Cleaning Products Supplier",
  "Consignment Shop",
  "Custom Confiscated Goods Store",
  "Do-it-Yourself Shop",
  "General Store",
  "Glassware Store",
  "Green Walls and Divides Store",
  "Hardware Accessories Store",
  "Hardware Store",
  "Home Goods Store",
  "Household Chemicals Supplier",
  "Junk Store",
  "Knife Manufacturing",
  "Light Bulb Supplier",
  "Lighting Store",
  "Mailbox Supplier",
  "Miniatures Store",
  "Neon Sign Shop",
  "Notions Store",
  "Novelty Store",
  "Safe and Vault Shop",
  "Second Hand Store",
  "Smart Shop",
  "Store",
  "Surplus Store",
  "Variety Store",
  "Burglar Alarm Store",
  "Curtain and Upholstery Cleaning Service",
  "Fire Alarm Supplier",
  "Flooring Store",
  "Furniture Repair Shop",
  "Garage Door Supplier",
  "Granite Supplier",
  "Home Improvement Store",
  "Lamp Repair Service",
  "Leather Cleaning Service",
  "Leather Repair Service",
  "Remodeler",
  "Security Equipment Store",
  "Upholstery Cleaning Service",
  "Window Treatment Store",
  "Air Duct Cleaning Service",
  "Beach Cleaning Service",
  "Blast Cleaning Service",
  "Carpet Cleaning Service",
  "Chimney Service",
  "Chimney Sweep",
  "Cleaners",
  "Cleaning Service",
  "Graffiti Removal Service",
  "House Cleaning Service",
  "Pool Cleaning Service",
  "Pressure Washing Service",
  "Render Cleaning Service",
  "Sandblasting Service",
  "Water Tank Cleaning Service",
  "Window Cleaning Service",
  "Bricklayer",
  "Carpenter",
  "Carpet Installer",
  "Electrical Installation Service",
  "Electrician",
  "Elevator Service",
  "Embossing Service",
  "Emergency Locksmith Service",
  "Floor Refinishing Service",
  "Floor Sanding and Polishing Service",
  "Flooring Contractor",
  "Handyman",
  "Key Duplication Service",
  "Linoleum Store",
  "Locks Supplier",
  "Locksmith",
  "Paint Stripping Company",
  "Painter",
  "Waterproofing Company",
  "Wood and Laminate Flooring Supplier",
  "Asbestos Testing Service",
  "Bird Control Service",
  "Double Glazing Installer",
  "Feng Shui Consultant",
  "Grounds Maintenance Service",
  "Homekill Service",
  "House Clearance Service",
  "Impermeabilization Service",
  "Lawn Care Service",
  "Lighting Consultant",
  "Snow Removal Service",
  "Soil Testing Service",
  "Vastu Consultant",
  "Water Damage Restoration Service",
  "Wood Floor Refinishing Service",
  "Fire Damage Restoration Service",
  "Fire Protection Consultant",
  "Fire Protection Service",
  "Home Inspector",
  "House Sitter",
  "House Sitter Agency",
  "Janitorial Service",
  "Security Service",
  "Security System Installer",
  "Security System Supplier",
  "Cold Storage Facility",
  "Moving and Storage Service",
  "Moving Company",
  "Moving Supply Store",
  "Piano Moving Service",
  "Records Storage Facility",
  "Self-Storage Facility",
  "Storage Facility",
  "Wine Storage Facility",
  "Gutter Cleaning Service",
  "Pest Control Service",
  "Plumber",
  "Sanitary Inspection",
  "Septic System Service",
  "Water Testing Service",
  "Clock Repair Service",
  "Copier Repair Service",
  "Fiberglass Repair Service",
  "Glass Repair Service",
  "Hot Tub Repair Service",
  "Radiator Repair Service",
  "Repair Service",
  "Screen Repair Service",
  "Small Engine Repair Service",
  "Stereo Repair Service",
  "VCR Repair Service",
  "Waterbed Repair Service",
  "Border Crossing Station",
  "Border Guard",
  "Customs Broker",
  "Customs Consultant",
  "Customs Department",
  "Customs Office",
  "Customs Warehouse",
  "Foreign Consulate",
  "Immigration and Naturalization Service",
  "Immigration Detention Centre",
  "Main Customs Office",
  "Toll Booth",
  "Toll Road Rest Stop",
  "Conservation Department",
  "Department for Regional Development",
  "Department of Education",
  "Department of Finance",
  "Department of Housing",
  "Department of Public Safety",
  "Department of Social Services",
  "Department of Transportation",
  "Dept of City Treasure",
  "Dept of State Treasure",
  "Embassy",
  "Emergency Management Ministry",
  "European Institution",
  "Federal Agency for Technical Relief",
  "Federal Government Office",
  "Government Economic Program",
  "Government Office",
  "Indian reserve (CA)",
  "Indian reserve (US)",
  "Japanese Prefecture Government Office",
  "Justice Department",
  "Land Reform Institute",
  "Land Surveying Office",
  "Lost Property Office",
  "Ministry of Education",
  "Public Health Department",
  "Public Works Department",
  "Regional Government Office",
  "Social Security Financial Department",
  "State Department Agricultural Development",
  "State Department Agriculture Food Supply",
  "State Department Civil Defense",
  "State Department Communication",
  "State Department Finance",
  "State Department for Social Development",
  "State Department Housing and Urban Development",
  "State Department of Environment",
  "State Department of Tourism",
  "State Department of Transportation",
  "State Department Science Technology",
  "State Department Social Defense",
  "State Dept of Culture",
  "State Dept of Sports",
  "State Employment Department",
  "State Government Office",
  "State Office of Education",
  "State Police",
  "State Social Development",
  "Urban Planning Department",
  "Veterans Affairs Department",
  "Bail Bonds Service",
  "Carabinieri Police",
  "Civil Police",
  "Coast Guard Station",
  "Court Executive Officer",
  "Court Reporter",
  "Crime Victim Service",
  "Detective",
  "Detention Center",
  "Federal Police",
  "Fingerprinting Service",
  "Forensic Consultant",
  "Guardia Di Finanza Police",
  "Highway Patrol",
  "Juvenile Detention Center",
  "Municipal Guard",
  "Police Supply Store",
  "Prison",
  "Private Investigator",
  "Probation Office",
  "Public Safety Office",
  "Sheriff's Department",
  "Traffic Officer",
  "Administrative Attorney",
  "Attorney Referral Service",
  "Bankruptcy Attorney",
  "Barrister",
  "Civil Law Attorney",
  "Criminal Justice Attorney",
  "District Attorney",
  "Divorce Lawyer",
  "Elder Law Attorney",
  "Employment Attorney",
  "Estate Planning Attorney",
  "Family Law Attorney",
  "General Practice Attorney",
  "Immigration Attorney",
  "Insurance Attorney",
  "Labor Relations Attorney",
  "Law Firm",
  "Lawyer",
  "Personal Injury Attorney",
  "Real Estate Attorney",
  "Tax Attorney",
  "Trial Attorney",
  "Bailiff",
  "Central Authority",
  "Commissioner for Oaths",
  "Conveyancer",
  "Correctional Services Department",
  "Divorce Service",
  "Executor",
  "Foreclosure Service",
  "Huissier",
  "Judicial Auction",
  "Judicial Scrivener",
  "Legal Affairs Bureau",
  "Legal Aid Office",
  "Legal Services",
  "Marriage License Bureau",
  "Mediation Service",
  "Notary Public",
  "Paralegal Services Provider",
  "Passport Agent",
  "Passport Office",
  "Prefecture",
  "Public Defender's Office",
  "Public Prosecutors Office",
  "Reclamation Centre",
  "Small Claims Assistance Service",
  "Title Company",
  "Archive",
  "Law Library",
  "Library",
  "Militar Archive",
  "Public Library",
  "State Archive",
  "City Administration",
  "City Clerk's Office",
  "City Courthouse",
  "City Department of Environment",
  "City Department of Public Safety",
  "City Department of Transportation",
  "City District Office",
  "City Employment Department",
  "City Government Office",
  "City Hall",
  "City Pillar Shrine",
  "City Tax Office",
  "Council",
  "Counselor",
  "County Government Office",
  "District Council",
  "District Government Office",
  "District Justice",
  "District Office",
  "Local Government Office",
  "Municipal Administration Office",
  "Municipal Corporation",
  "Municipal Department Agricultural Development",
  "Municipal Department Agriculture Food Supply",
  "Municipal Department Civil Defense",
  "Municipal Department Communication",
  "Municipal Department Finance",
  "Municipal Department Housing and Urban Development",
  "Municipal Department of Culture",
  "Municipal Department of Sports",
  "Municipal Department of Tourism",
  "Municipal Department Science Technology",
  "Municipal Department Social Defense",
  "Municipal Health Department",
  "Municipal Office Education",
  "Municipal Social Development",
  "Provincial Council",
  "Regional Council",
  "Tribal Headquarters",
  "Certification Agency",
  "Civil Registry",
  "Company Registry",
  "Driver's License Office",
  "Driver and Vehicle Licensing Agency",
  "General Register Office",
  "Intellectual Property Registry",
  "License Bureau",
  "Property Registry",
  "Registration Chamber",
  "Registration Office",
  "Registry Office",
  "Resident Registration Office",
  "Tag Agency",
  "Voter Registration Office",
  "Voting Facility",
  "Book Publisher",
  "Book Store",
  "Bookbinder",
  "Books Wholesaler",
  "Childrens Book Store",
  "Christian Book Store",
  "Comic Book Store",
  "Law Book Store",
  "Magazine Store",
  "Medical Book Store",
  "Multimedia and Electronic Book Publisher",
  "Publisher",
  "Rare Book Store",
  "Record Store",
  "Religious Book Store",
  "Used Book Store",
  "Blogger",
  "Classified Ads Newspaper Publisher",
  "Communications Central",
  "Media and Marketing Agency",
  "Media Company",
  "Media House",
  "News Cooperation",
  "News Service",
  "Newspaper Advertising Department",
  "Newspaper Distribution",
  "Newspaper Publisher",
  "Newsstand",
  "Press Advisory",
  "Public Relations Firm",
  "Radio Broadcaster",
  "Social Media Agency",
  "Television Station",
  "Aerial Photographer",
  "Model Portfolio Studio",
  "Modeling Agency",
  "Passport Photo Processor",
  "Photo Agency",
  "Photo Printing Service",
  "Photocopiers Supplier",
  "Photographer",
  "Photography Service",
  "Photography Studio",
  "Portrait Studio",
  "Animation Studio",
  "Audio Visual Consultant",
  "Audio Visual Equipment Supplier",
  "CD Store",
  "Cinema Equipment Supplier",
  "DVD Store",
  "Film and Video Producer",
  "Film Production Company",
  "Home Cinema Installation",
  "Movie Studio",
  "Music Box Store",
  "Music Management and Promotion",
  "Music Producer",
  "Music Publisher",
  "Music Store",
  "Printed Music Publisher",
  "Record Company",
  "Recording Studio",
  "Used CD Store",
  "Video Conferencing Equipment Supplier",
  "Video Duplication Service",
  "Video Editing Service",
  "Video Production Service",
  "Accountant",
  "Accounting Firm",
  "Bankruptcy Service",
  "Bookkeeping Service",
  "Certified Public Accountant",
  "Chartered Accountant",
  "Tax Advisor",
  "Tax Assessor",
  "Tax Collector's Office",
  "Tax Consultant",
  "Tax Department",
  "Tax Preparation",
  "Tax Preparation Service",
  "Tax Preparation Software",
  "ATM",
  "Bank",
  "Cashback Provider",
  "Central Bank",
  "Check Cashing Service",
  "Cryptocurrency Service",
  "Currency Exchange Service",
  "Escrow Service",
  "Federal Reserve Bank",
  "Financial Institution",
  "Mobile Money Agent",
  "Money Order Service",
  "Money Transfer Service",
  "Private Sector Bank",
  "Public Sector Bank",
  "Savings Bank",
  "Shinkin Bank",
  "Trust Bank",
  "Credit Bureau",
  "Credit Counseling Service",
  "Credit Reporting Agency",
  "Credit Union",
  "Debt Collecting",
  "Debt Collection Agency",
  "Debt Relief Service",
  "Estate Liquidator",
  "Federal Credit Union",
  "Insolvency Service",
  "Liquidator",
  "Loss Adjuster",
  "Pawn Shop",
  "Accident Insurance Company",
  "Auto Insurance Agency",
  "Business Insurance Company",
  "Caravan and Motorhome Insurance Company",
  "Commercial Insurance Company",
  "Cycle Insurance Company",
  "Dental Insurance Agency",
  "Disability Insurance Company",
  "Funeral Insurance Company",
  "Gadget Insurance Company",
  "Health Insurance Agency",
  "Home Insurance Agency",
  "Income Protection Insurance Company",
  "Insurance Agency",
  "Insurance Broker",
  "Insurance Company",
  "Jewelry and Watch Insurance Company",
  "Key Man Insurance Company",
  "Landlord Insurance Company",
  "Legal Expenses Insurance Company",
  "Liability Insurance Company",
  "Life Insurance Agency",
  "Mobility Insurance Company",
  "Motorcycle Insurance Agency",
  "Personal Insurance Company",
  "Pet Insurance Company",
  "Renter's Insurance Agency",
  "Sports Insurance Company",
  "Storage Insurance Company",
  "Student Insurance Company",
  "Tax Investigation Insurance Company",
  "Taxi Insurance Company",
  "Term Life Insurance Provider Company",
  "Travel Insurance Company",
  "Agenzia Entrate",
  "Alternative Financial Service",
  "Asset Manager Service",
  "Board of Trade",
  "Car Finance and Loan Company",
  "Economic Consultant",
  "Economic Development Agency",
  "Estate Appraiser",
  "Finance Broker",
  "Financial Audit",
  "Financial Consultant",
  "Financial Planner",
  "Fund Management Company",
  "Gold and Silver Trading Company",
  "Gold Dealer",
  "Holding Company",
  "Investment Bank",
  "Investment Company",
  "Investment Service",
  "Loan Agency",
  "Mortgage Broker",
  "Mortgage Lender",
  "Non-Bank Financial Service",
  "Pension Fund",
  "Pension Office",
  "Private Equity Firm",
  "Property Investment",
  "Retirement Scheme Provider",
  "Shareholder Protection Company",
  "Stock Broker",
  "Stock Exchange Building",
  "Trust Fund",
  "Venture Capital Company",
  "Apartment Building",
  "Apartment Complex",
  "Apartment Rental Agency",
  "Appraiser",
  "Condominium Complex",
  "Condominium Rental Agency",
  "Country House",
  "Group Buying Service",
  "Group Home",
  "Housing Complex",
  "Modular Home Dealer",
  "Property Administrator",
  "Property Management Company",
  "Real Estate Agency",
  "Real Estate Agents",
  "Real Estate Appraiser",
  "Real Estate Auctioneer",
  "Real Estate Consultant",
  "Real Estate Developer",
  "Real Estate Fair",
  "Real Estate Rental Agency",
  "Short Term Apartment Rental Agency",
  "Career Guidance Service",
  "Coaching Center",
  "Emergency Training",
  "Employment Agency",
  "Employment Center",
  "Employment Search Service",
  "Social Worker",
  "Training Centre",
  "Tutoring Service",
  "Unemployment Office",
  "Casket Service",
  "Cemetery",
  "Coffin Supplier",
  "Cremation Service",
  "Funeral Director",
  "Funeral Home",
  "Memorial Estate",
  "Memorial Park",
  "Mortuary",
  "Building Society",
  "Homeowners Association",
  "Housing Association",
  "Housing Authority",
  "Housing Cooperative",
  "Housing Society",
  "Low Income Housing Program",
  "Manor House",
  "Rectory",
  "Residents Association",
  "Roommate Referral Service",
  "Sokol House",
  "Tenant's Union",
  "Tenant Ownership",
  "Babysitter",
  "Child Care Agency",
  "Child Care Center",
  "Childrens Home",
  "Creche",
  "Diaper Service",
  "Genealogist",
  "Kindergarten",
  "Part Time Daycare",
  "Waldorf Kindergarten",
  "Armed Forces Association",
  "Army Barracks",
  "Army Facility",
  "Civil Defence",
  "Ground Self Defense Force",
  "Guardia Civil",
  "Marine Self Defense Force",
  "Militar Residence",
  "Military Barracks",
  "Military Base",
  "Military Board",
  "Military Cemetery",
  "Military Recruiting Office",
  "Military Town",
  "Naval Base",
  "RSL Club",
  "United States Armed Forces Base",
  "Veterans Center",
  "Veterans Organization",
  "Animal Protection Organization",
  "Ecologists Association",
  "Environment Office",
  "Environmental Consultant",
  "Environmental Health Service",
  "Environmental Organization",
  "Environmental Protection Organization",
  "Environmental Renewable Natural Resources",
  "Forestry Service",
  "Garden",
  "Geological Research Company",
  "Geological Service",
  "Geologist",
  "Low Emission Zone",
  "Mine",
  "Superfund Site",
  "Time and Temperature Announcement Service",
  "Weather Forecast Service",
  "Weir",
  "Aboriginal and Torres Strait Islander Organisation",
  "Agricultural Association",
  "Agricultural Organization",
  "Architects Association",
  "Arts Organization",
  "Association or Organization",
  "Charity",
  "Conservative Club",
  "Convenience Stores Organization",
  "Cultural Association",
  "Donations Center",
  "Fair Trade Organization",
  "Foreman Builders Association",
  "Foundation",
  "Fraternal Organization",
  "Gay and Lesbian Organization",
  "Income Tax Help Association",
  "Industrial Engineers Association",
  "Industrial Technical Engineers Association",
  "Labor Union",
  "Labour Club",
  "Lawyers Association",
  "Literacy Program",
  "Livery Company",
  "Maori Organization",
  "Markmens Clubhouse",
  "Missing Persons Organization",
  "Non-Governmental Organization",
  "Non-Profit Organization",
  "Notaries Association",
  "Nursing Association",
  "Patients Support Association",
  "Political Party",
  "Professional and Hobby Associations",
  "Roads Ports and Canals Engineers Association",
  "Sacem",
  "Singles Organization",
  "Social Club",
  "Students Parents Association",
  "Students Support Association",
  "Volunteer Organization",
  "Women's Organization",
  "Workers Club",
  "Youth Organization",
  "Youth Social Services Organization",
  "Assembly Room",
  "Citizen Information Bureau",
  "Citizens Advice Bureau",
  "City Park",
  "Civic Center",
  "Community Center",
  "Community Garden",
  "Consumer Advice Center",
  "Convention Information Bureau",
  "Favela",
  "Fire Station",
  "Information Bureau",
  "Information Service",
  "Post Office",
  "Public Amenity House",
  "Public Bathroom",
  "Public Female Bathroom",
  "Public Housing",
  "Public Male Bathroom",
  "Public Parking Space",
  "Public Webcam",
  "Public Wheelchair-Accessible Bathroom",
  "Road camera",
  "Sheltered Housing",
  "Social Security Attorney",
  "Social Security Office",
  "Social Services Organization",
  "Social Welfare Center",
  "Townhouse Complex",
  "Villa",
  "Women's Protection Service",
  "Abbey",
  "Abundant Life Church",
  "Alliance Church",
  "Anglican Church",
  "Apostolic Church",
  "Armenian Church",
  "Ashram",
  "Assemblies of God Church",
  "Baha'i House of Worship",
  "Baptist Church",
  "Basilica",
  "Buddhist Supplies Store",
  "Buddhist Temple",
  "Calvary Chapel Church",
  "Cathedral",
  "Catholic Cathedral",
  "Catholic Church",
  "Chapel",
  "Christian Church",
  "Church",
  "Church of Christ",
  "Church of Jesus Christ of Latter-day Saints",
  "Church of the Nazarene",
  "Church Supply Store",
  "Clergyman",
  "Congregation",
  "Conservative Synagogue",
  "Deaf Church",
  "Disciples of Christ Church",
  "Eastern Orthodox Church",
  "Episcopal Church",
  "Evangelical Church",
  "Foursquare Church",
  "Friends Church",
  "Full Gospel Church",
  "Gospel Church",
  "Greek Orthodox Church",
  "Gurudwara",
  "Hindu Priest",
  "Hindu Temple",
  "Hispanic Church",
  "Jain Temple",
  "Jehovah's Witness Kingdom Hall",
  "Korean Church",
  "Lutheran Church",
  "Marae",
  "Masonic Center",
  "Mennonite Church",
  "Messianic Synagogue",
  "Methodist Church",
  "Mission",
  "Monastery",
  "Moravian Church",
  "Mosque",
  "New Age Church",
  "Non-Denominational Church",
  "Nunnery",
  "Orthodox Church",
  "Orthodox Synagogue",
  "Parish",
  "Parsi Temple",
  "Pentecostal Church",
  "Pilgrimage Place",
  "Place of Worship",
  "Presbyterian Church",
  "Priest",
  "Protestant Church",
  "Quaker Church",
  "Reform Synagogue",
  "Reformed Church",
  "Religious Destination",
  "Religious Goods Store",
  "Religious Institution",
  "Religious Organization",
  "Religious Seminary",
  "Russian Orthodox Church",
  "Seventh-day Adventist Church",
  "Shinto Shrine",
  "Shrine",
  "Spiritist Center",
  "Synagogue",
  "Taoist Temple",
  "Unitarian Universalist Church",
  "United Church of Canada",
  "United Church of Christ",
  "United Methodist Church",
  "Unity Church",
  "Vineyard Church",
  "Wesleyan Church",
  "Yeshiva",
  "Aged Care",
  "Boarding House",
  "Homeless Service",
  "Homeless Shelter",
  "Orphan Asylum",
  "Orphanage",
  "Refugee Camp",
  "Retirement Community",
  "Retirement Home",
  "School Youth Hostel",
  "Senior Citizen Center",
  "Women's Shelter",
  "Working Women's Hostel",
  "Youth Hostel",
  "Zac",
  "Bottle and Can Redemption Center",
  "Chemical Exporter",
  "Drainage Service",
  "Garbage Collection Service",
  "Garbage Dump",
  "Garbage Dump Service",
  "Incineration Plant",
  "Recycling Center",
  "Salvage Yard",
  "Sewage Disposal Service",
  "Sewage Treatment Plant",
  "Solid Waste Engineer",
  "Waste Management Service",
  "African Restaurant",
  "Australian Restaurant",
  "Cape Verdean Restaurant",
  "East African Restaurant",
  "Eritrean Restaurant",
  "Ethiopian Restaurant",
  "Hawaiian Restaurant",
  "Moroccan Restaurant",
  "Nasi Uduk Restaurant",
  "New Zealand Restaurant",
  "North African Restaurant",
  "Polynesian Restaurant",
  "Seychelles Restaurant",
  "South African Restaurant",
  "Tunisian Restaurant",
  "West African Restaurant",
  "Bar",
  "Bar and Grill",
  "Bar PMU",
  "Bar Tabac",
  "Cafe",
  "Cafeteria",
  "Chocolate Cafe",
  "Cider Bar",
  "Cocktail Bar",
  "Cured Ham Bar",
  "Espresso Bar",
  "Gastropub",
  "Grand Cafe",
  "Hookah Bar",
  "Irish Pub",
  "Karaoke Bar",
  "Live Music Bar",
  "Oxygen Cocktail Spot",
  "Oyster Bar Restaurant",
  "Piano Bar",
  "Pub",
  "Salsa Bar",
  "Snack Bar",
  "Sports Bar",
  "Stand Bar",
  "Tapas Bar",
  "Wine Bar",
  "An Hui Restaurant",
  "Cantonese Restaurant",
  "Chinese Noodle Restaurant",
  "Chinese Restaurant",
  "Dan Dan Noodle Restaurant",
  "Delivery Chinese Restaurant",
  "Dim Sum Restaurant",
  "Dong Bei restaurant",
  "Dumpling Restaurant",
  "Fu Jian Restaurant",
  "Gui Zhou Restaurant",
  "Hakka Restaurant",
  "Hong Kong Style Fast Food Restaurant",
  "Hot Pot Restaurant",
  "Huaiyang style restaurant",
  "Hubei Style Restaurant",
  "Hunan Restaurant",
  "Jiang Su Restaurant",
  "Korean Barbecue Restaurant",
  "Korean Beef Restaurant",
  "Korean Restaurant",
  "Korean Rib Restaurant",
  "Mandarin Restaurant",
  "Mongolian Barbecue Restaurant",
  "Nyonya Restaurant",
  "Rice Restaurant",
  "Shan Dong Restaurant",
  "Shanghainese Restaurant",
  "Shanxi Style Restaurant",
  "Sichuan Restaurant",
  "Singaporean Restaurant",
  "Soondae restaurant",
  "Taiwanese Restaurant",
  "Tongue Restaurant",
  "Xiang Cuisine Restaurant",
  "Zhe Jiang Restaurant",
  "Alsace Restaurant",
  "Armenian Restaurant",
  "Austrian Restaurant",
  "Basque Restaurant",
  "Belgian Restaurant",
  "British Restaurant",
  "Bulgarian Restaurant",
  "Cantabrian Restaurant",
  "Carvery",
  "Continental Restaurant",
  "Czech Restaurant",
  "Danish Restaurant",
  "Dutch Restaurant",
  "Eastern European Restaurant",
  "English Restaurant",
  "European Restaurant",
  "Finnish Restaurant",
  "Fish and Chips Restaurant",
  "Fondue Restaurant",
  "French Restaurant",
  "French Steakhouse Restaurant",
  "Georgian Restaurant",
  "German Restaurant",
  "Hungarian Restaurant",
  "Icelandic Restaurant",
  "Irish Restaurant",
  "Kazakhstani Restaurant",
  "Lithuanian Restaurant",
  "Mid-Atlantic Restaurant",
  "Modern British Restaurant",
  "Norwegian Restaurant",
  "Polish Restaurant",
  "Raclette Restaurant",
  "Romanian Restaurant",
  "Russian Restaurant",
  "Scandinavian Restaurant",
  "Serbian Restaurant",
  "Southwest France Restaurant",
  "Swedish Restaurant",
  "Swiss Restaurant",
  "Ukrainian Restaurant",
  "Welsh Restaurant",
  "Angler Fish Restaurant",
  "Asian Fusion Restaurant",
  "Berry Restaurant",
  "Breakfast Restaurant",
  "Brunch Restaurant",
  "Buffet Restaurant",
  "Cheesesteak Restaurant",
  "Chicken Restaurant",
  "Chicken Wings Restaurant",
  "Country Food Restaurant",
  "Couscous Restaurant",
  "Crab House",
  "Creole Restaurant",
  "Dance Restaurant",
  "Dessert Restaurant",
  "Down Home Cooking Restaurant",
  "Eclectic Restaurant",
  "Ethnic Restaurant",
  "Family Restaurant",
  "Fusion Restaurant",
  "Honduran Restaurant",
  "Lunch Restaurant",
  "Meat Dish Restaurant",
  "Nicaraguan Restaurant",
  "Pancake Restaurant",
  "Porridge Restaurant",
  "Restaurant",
  "Restaurant Supply Store",
  "Seafood Restaurant",
  "Self-Service Restaurant",
  "Soup Restaurant",
  "Steak House",
  "Sundae Restaurant",
  "Surinamese Restaurant",
  "Traditional Restaurant",
  "Anago Restaurant",
  "Authentic Japanese Restaurant",
  "Champon Noodle Restaurant",
  "Chanko Restaurant",
  "Conveyor Belt Sushi Restaurant",
  "Dojo Restaurant",
  "Fugu Restaurant",
  "Gyudon Restaurant",
  "Izakaya Restaurant",
  "Japanese Curry Restaurant",
  "Japanese Regional Restaurant",
  "Japanese Restaurant",
  "Japanese Sweets Restaurant",
  "Japanized Western Restaurant",
  "Kaiseki Restaurant",
  "Katsudon Restaurant",
  "Kushiage and Kushikatsu Restaurant",
  "Kushiyaki Restaurant",
  "Kyoto Style Japanese Restaurant",
  "Miso Cutlet Restaurant",
  "Modern Izakaya Restaurants",
  "Monjayaki Restaurant",
  "Obanzai Restaurant",
  "Oden Restaurant",
  "Okonomiyaki Restaurant",
  "Ramen Restaurant",
  "Ryotei Restaurant",
  "Seafood Donburi Restaurant",
  "Shabu-shabu Restaurant",
  "Sukiyaki and Shabu Shabu Restaurant",
  "Sukiyaki Restaurant",
  "Suppon Restaurant",
  "Sushi Restaurant",
  "Sushi takeaway",
  "Syokudo and Teishoku Restaurant",
  "Takoyaki Restaurant",
  "Tempura Donburi Restaurant",
  "Tempura Restaurant",
  "Teppanyaki Restaurant",
  "Tonkatsu Restaurant",
  "Udon Noodle Restaurant",
  "Unagi Restaurant",
  "Yakiniku Restaurant",
  "Yakitori Restaurant",
  "Andalusian Restaurant",
  "Asturian Restaurant",
  "Bistro",
  "Brasserie",
  "Castilian Restaurant",
  "Catalonian Restaurant",
  "Croatian Restaurant",
  "Extremadurian restaurant",
  "Fine Dining Restaurant",
  "Galician Restaurant",
  "Greek Restaurant",
  "Gyro Restaurant",
  "Haute French Restaurant",
  "Italian Restaurant",
  "Ligurian restaurant",
  "Madrilian Restaurant",
  "Majorcan Restaurant",
  "Maltese Restaurant",
  "Marche Restaurant",
  "Mediterranean Restaurant",
  "Modern European Restaurant",
  "Modern French Restaurant",
  "Navarraise Restaurant",
  "Neapolitan Restaurant",
  "Northern Italian Restaurant",
  "Offal Pot Cooking Restaurant",
  "Piedmontese restaurant",
  "Pizza Restaurant",
  "Portuguese Restaurant",
  "Provence Restaurant",
  "Roman Restaurant",
  "Sardinian restaurant",
  "Sicilian Restaurant",
  "Southern Italian Restaurant",
  "Spanish Restaurant",
  "Tapas Restaurant",
  "Tuscan Restaurant",
  "Valencian Restaurant",
  "Venetian Restaurant",
  "Afghani Restaurant",
  "Egyptian Restaurant",
  "Falafel Restaurant",
  "Halal Restaurant",
  "Israeli Restaurant",
  "Jewish Restaurant",
  "Kashmiri Restaurant",
  "Kosher Restaurant",
  "Lebanese Restaurant",
  "Lombardian Restaurant",
  "Middle Eastern Restaurant",
  "Murtabak Restaurant",
  "Pakistani Restaurant",
  "Persian Restaurant",
  "Sfiha restaurant",
  "Syrian Restaurant",
  "Turkish Restaurant",
  "Turkmen Restaurant",
  "Uzbeki Restaurant",
  "Yemenite Restaurant",
  "American Restaurant",
  "Argentinian Restaurant",
  "Brazilian pastelaria",
  "Brazilian Restaurant",
  "Burrito Restaurant",
  "Cajun Restaurant",
  "Californian Restaurant",
  "Canadian Restaurant",
  "Caribbean Restaurant",
  "Central American Restaurant",
  "Chesapeake Restaurant",
  "Chilean Restaurant",
  "Chophouse Restaurant",
  "Colombian Restaurant",
  "Contemporary Louisiana Restaurant",
  "Costa Rican Restaurant",
  "Cuban Restaurant",
  "Diner",
  "Dominican Restaurant",
  "Ecuadorian Restaurant",
  "Floridian Restaurant",
  "Guatemalan Restaurant",
  "Haitian Restaurant",
  "Jamaican Restaurant",
  "Latin American Restaurant",
  "Mexican Restaurant",
  "Mexican torta restaurant",
  "Native American Restaurant",
  "New American Restaurant",
  "New England Restaurant",
  "Nuevo Latino Restaurant",
  "Oaxacan restaurant",
  "Pacific Northwest American Restaurant",
  "Pacific Northwest Restaurant (Canada)",
  "Pacific Rim Restaurant",
  "Pan-Latin Restaurant",
  "Paraguayan Restaurant",
  "Pennsylvania Dutch Restaurant",
  "Peruvian Restaurant",
  "Po Boy Restaurant",
  "Pozole restaurant",
  "Pueblan restaurant",
  "Puerto Rican Restaurant",
  "Quebecois Restaurant",
  "Salvadoran Restaurant",
  "South American Restaurant",
  "Southern American Restaurant",
  "Southwestern American Restaurant",
  "Steamboat Restaurant",
  "Tabascan restaurant",
  "Taco Restaurant",
  "Tamale Shop",
  "Tex-Mex Restaurant",
  "Traditional American Restaurant",
  "Uruguayan Restaurant",
  "Venezuelan Restaurant",
  "Western Restaurant",
  "Yucatan restaurant",
  "Asian Restaurant",
  "Bakso Restaurant",
  "Balinese Restaurant",
  "Bangladeshi Restaurant",
  "Batak restaurant",
  "Betawi Restaurant",
  "Biryani restaurant",
  "Burmese Restaurant",
  "Cambodian Restaurant",
  "Central Javanese restaurant",
  "Chettinad restaurant",
  "Cold Noodle Restaurant",
  "East Javanese restaurant",
  "Filipino Restaurant",
  "Goan restaurant",
  "Ikan bakar restaurant",
  "Indian Curry Restaurant",
  "Indian Muslim Restaurant",
  "Indian Restaurant",
  "Indian sizzler restaurant",
  "Indonesian Restaurant",
  "Javanese restaurant",
  "Karnataka Restaurant",
  "Konkani restaurant",
  "Laotian Restaurant",
  "Malaysian Restaurant",
  "Manado Restaurant",
  "Modern Indian restaurant",
  "Nasi Goreng Restaurant",
  "Nepalese Restaurant",
  "North Eastern Indian restaurant",
  "Padang restaurant",
  "Pan-Asian Restaurant",
  "Parsi restaurant",
  "Pecel Lele Restaurant",
  "Pempek Restaurant",
  "Pho Restaurant",
  "Punjabi Restaurant",
  "Satay restaurant",
  "Soto ayam restaurant",
  "South Asian Restaurant",
  "South Sulawesi restaurant",
  "Southeast Asian Restaurant",
  "Sri Lankan Restaurant",
  "Sundanese restaurant",
  "Thai Restaurant",
  "Vietnamese Restaurant",
  "Wok Restaurant",
  "Barbecue Restaurant",
  "Fast Food Restaurant",
  "Fish and Chips Takeaway",
  "Fried Chicken Takeaway",
  "Frituur",
  "Hamburger Restaurant",
  "Hoagie Restaurant",
  "Hot Dog Restaurant",
  "Hot Dog Stand",
  "Indian Takeaway",
  "Kebab Shop",
  "Meal Takeaway",
  "Mutton Barbecue Restaurant",
  "Offal Barbecue Restaurant",
  "Online Food Ordering Service",
  "Pizza Delivery",
  "Pizza Takeaway",
  "Sandwich Shop",
  "Take Away Service",
  "Gluten-Free Restaurant",
  "Health Food Restaurant",
  "Macrobiotic Restaurant",
  "Organic Restaurant",
  "Raw Food Restaurant",
  "Small Plates Restaurant",
  "Soul Food Restaurant",
  "Tofu Restaurant",
  "Vegan Restaurant",
  "Vegetarian Cafe and Deli",
  "Vegetarian Restaurant",
  "Bag Shop",
  "Bags and Luggage Store",
  "Belt Shop",
  "Fashion Accessories Store",
  "Handbags Shop",
  "Hat Shop",
  "Headwear Store",
  "Knit Shop",
  "Luggage Store",
  "Sunglasses Store",
  "Wig Shop",
  "Activewear Store",
  "Baby Clothing Store",
  "Baby Store",
  "Beach Clothing Store",
  "Boot Store",
  "Children's Clothing Store",
  "Clothing Store",
  "Clothing Supplier",
  "Couture Store",
  "Custom T-Shirt Store",
  "Custom Tailor",
  "Felt Boots Store",
  "Fur Coat Shop",
  "Fur Service",
  "Haute Couture Fashion House",
  "Jeans Shop",
  "Leather Coats Store",
  "Lingerie Manufacturer",
  "Lingerie Store",
  "Maternity Store",
  "Men's Clothing Store",
  "Men's Tailor",
  "Outdoor Clothing and Equipment Shop",
  "Outerwear Store",
  "Plus Size Clothing Store",
  "Printed Clothing Store",
  "Sheepskin Coat Store",
  "Shoe Factory",
  "Shoe Shining Service",
  "Shoe Store",
  "Sportswear Store",
  "Sportwear Manufacturer",
  "Streetwear Store",
  "Swimwear Store",
  "T-Shirt Company",
  "T-Shirt Store",
  "Thrift Store",
  "Underwear Store",
  "Used Clothing Store",
  "Vintage Clothing Store",
  "Winterwear Store",
  "Women's Clothing Store",
  "Work Clothes Store",
  "Youth Clothing Store",
  "Boot Repair Shop",
  "Clothing Alteration Service",
  "Costume Rental Service",
  "Dry Cleaner",
  "Kilt Shop and Hire",
  "Laundromat",
  "Laundry",
  "Laundry Service",
  "Luggage Repair Service",
  "Shoe Repair Shop",
  "Tailor",
  "Watch Repair Service",
  "Army & Navy Surplus Shop",
  "Bridal Shop",
  "Costume Store",
  "Dress and Tuxedo Rental Service",
  "Dress Store",
  "Dressmaker",
  "Evening Dress Rental Service",
  "Formal Wear Store",
  "Full Dress Rental Service",
  "Kimono Store",
  "Theatrical Costume Supplier",
  "Traditional Costume Club",
  "Traditional Costume Store",
  "Tuxedo Shop",
  "Uniform Store",
  "Wedding Dress Rental Service",
  "Western Apparel Store",
  "Clock Watch Maker",
  "Costume Jewelry Shop",
  "Diamond Buyer",
  "Diamond Dealer",
  "Jeweler",
  "Jewellery Manufacturer",
  "Jewelry Appraiser",
  "Jewelry Buyer",
  "Jewelry Designer",
  "Jewelry Engraver",
  "Jewelry Exporter",
  "Jewelry Repair Service",
  "Jewelry Store",
  "Watch Manufacturer",
  "Watch Store",
  "Bazar",
  "Christmas Market",
  "Clothes Market",
  "Coupon Service",
  "Department Store",
  "Discount Store",
  "Dollar Store",
  "Duty-Free Store",
  "Flea Market",
  "Floating Market",
  "Hua Gong Shop",
  "Hua Hui Market Place",
  "Hua Niao Market Place",
  "Hypermarket",
  "Night Market",
  "Online Auction Service",
  "Online Marketplace",
  "Outlet Mall",
  "Outlet Store",
  "Price Comparison Site",
  "Review Site",
  "Shopping Mall",
  "Souvenir Store",
  "Traditional Market",
  "Warehouse club",
  "Warehouse store",
  "Basketball Club",
  "Basketball Court",
  "Basketball Court Contractor",
  "Beach Volleyball Club",
  "Beach Volleyball Court",
  "Bocce Ball Court",
  "Dodgeball Club",
  "Football Club",
  "Football Field",
  "Futsal Court",
  "Handball Club",
  "Handball Court",
  "Netball Club",
  "Rugby",
  "Rugby Club",
  "Rugby Field",
  "Rugby League Club",
  "Rugby Store",
  "Soccer Club",
  "Soccer Field",
  "Soccer Practice",
  "Soccer Store",
  "Volleyball Club",
  "Volleyball Court",
  "Volleyball Instructor",
  "Baseball",
  "Baseball Club",
  "Baseball Field",
  "Baseball Goods Store",
  "Batting Cage Center",
  "Cricket Club",
  "Cricket Ground",
  "Cricket Shop",
  "Little League Club",
  "Little League Field",
  "Softball Club",
  "Softball Field",
  "Billiards Supply Store",
  "Bowling Alley",
  "Bowling Club",
  "Bowling Supply Shop",
  "Croquet Club",
  "Curling Club",
  "Curling Hall",
  "Hurling Club",
  "Lawn Bowls Club",
  "Pool Academy",
  "Pool Billard Club",
  "Pool Hall",
  "Skittle Club",
  "Aero Dance Class",
  "Athletic Dancing School",
  "Ballet School",
  "Ballroom Dance Instructor",
  "Cheerleading Club",
  "Dance Club",
  "Dance Company",
  "Dance Conservatory",
  "Dance Hall",
  "Dance Pavillion",
  "Dance School",
  "Dance Store",
  "Flamenco Dance Store",
  "Flamenco School",
  "Gymnastics Center",
  "Gymnastics Club",
  "Hip Hop Dance Class",
  "Salsa Classes",
  "Samba School",
  "Leagues Club",
  "Sporting Goods Store",
  "Sports Card Store",
  "Sports Club",
  "Sports Complex",
  "Sports Equipment Rental Service",
  "Sports Memorabilia Store",
  "Sports Nutrition Store",
  "Sports School",
  "Adventure Sports",
  "Adventure Sports Center",
  "Aerial Sports Center",
  "Aeroclub",
  "Canoe and Kayak Club",
  "Canoe and Kayak Rental Service",
  "Canoe and Kayak Store",
  "Dive Shop",
  "Diving Center",
  "Fencing Club",
  "Fencing Salon",
  "Fencing School",
  "Go-Kart Track",
  "Hang Gliding Center",
  "Kite Shop",
  "Motorsports Store",
  "Mountaineering Class",
  "Parachuting Club",
  "Parasailing Ride Service",
  "Parkour Club",
  "Rafting",
  "Roller Skating Club",
  "Roller Skating Rink",
  "Skate Sharpening Service",
  "Skate Shop",
  "Skateboard Park",
  "Skateboard Shop",
  "Skating Instructor",
  "Skydiving Center",
  "Snowboard Rental Service",
  "Snowboard Shop",
  "Surf Lifesaving Club",
  "Surf School",
  "Surf Shop",
  "Windsurfing Store",
  "Aerobics Instructor",
  "Disabled Sports Center",
  "Fitness Center",
  "Fitness class",
  "Fitness Equipment Store",
  "Fitness Equipment Wholesaler",
  "Gym",
  "Personal Trainer",
  "Physical Fitness Program",
  "Weightlifting Area",
  "Weightlifting Club",
  "Women's Personal Trainer",
  "Disc Golf Course",
  "Golf Club",
  "Golf Course",
  "Golf Driving Range",
  "Golf Instructor",
  "Golf shop",
  "Indoor Golf Course",
  "Miniature Golf Course",
  "Private Golf Course",
  "Public Golf Course",
  "Ultimate Club",
  "Hockey Club",
  "Hockey Field",
  "Hockey Rink",
  "Hockey Store",
  "Ice Hockey Club",
  "Ice Skating Club",
  "Ice Skating Instructor",
  "Ice Skating Rink",
  "Aikido Club",
  "Aikido School",
  "Boxing Club",
  "Boxing Gym",
  "Boxing Ring",
  "Capoeira School",
  "Freestyle Wrestling",
  "Greco Roman Wrestling",
  "Judo Club",
  "Judo School",
  "Jujitsu School",
  "Kabaddi Club",
  "Karate Club",
  "Karate School",
  "Kickboxing School",
  "Kung Fu School",
  "Martial Arts Club",
  "Martial Arts School",
  "Martial Arts Supply Store",
  "Mixed Martial Arts Club",
  "Muay Thai Boxing Gym",
  "Sambo School",
  "Tae Kwon Do Comp Area",
  "Taekwondo School",
  "Tai Chi School",
  "Wing Chun School",
  "Wrestling Club",
  "Wrestling School",
  "Athletic Club",
  "Athletic Field",
  "Athletic Park",
  "Athletic Track",
  "Bicycle Club",
  "BMX Club",
  "BMX Park",
  "BMX Track",
  "Bullring",
  "Climbing Club",
  "Cycling Park",
  "Equestrian Club",
  "Equestrian Facility",
  "Equestrian Store",
  "Indoor Cycling",
  "Orienteering Club",
  "Outdoor Equestrian Facility",
  "Outdoor Sports Store",
  "Polo Club",
  "Racecourse",
  "Road Cycling",
  "Rock Climbing",
  "Rock Climbing Gym",
  "Rock Climbing Instructor",
  "Rodeo",
  "Running Club",
  "Running Store",
  "Ski Club",
  "Ski Rental Service",
  "Ski Repair Service",
  "Ski School",
  "Ski Shop",
  "Triathlon Club",
  "Velodrome",
  "Winter sport Store",
  "Archery Club",
  "Archery Event",
  "Archery Hall",
  "Archery Range",
  "Archery Store",
  "Dart Supply Store",
  "Paintball Center",
  "Paintball Club",
  "Paintball Store",
  "Shooting Event Area",
  "Shooting Range",
  "Skeet Shooting Range",
  "Acrobatic Diving Pool",
  "Diving Club",
  "Padel Club",
  "Padel Court",
  "Rowing Area",
  "Rowing Club",
  "Sailing Club",
  "Sailing Store",
  "SCUBA Instructor",
  "Swim Club",
  "Swimming Basin",
  "Swimming Competition",
  "Swimming Facility",
  "Swimming Instructor",
  "Swimming Lake",
  "Swimming Pool",
  "Swimming School",
  "Water Polo Pool",
  "Water Ski Shop",
  "Water Skiing Club",
  "Water Skiing Instructor",
  "Water Skiing Service",
  "Water Sports Equipment Rental Service",
  "Badminton Club",
  "Badminton Complex",
  "Badminton Court",
  "Lacrosse Club",
  "Racquetball Club",
  "Squash Club",
  "Squash Court",
  "Table Tennis Club",
  "Table Tennis Facility",
  "Table Tennis Supply Store",
  "Tennis Club",
  "Tennis Court",
  "Tennis Instructor",
  "Tennis Store",
  "Beach Resort",
  "Bed & Breakfast",
  "Budget Japanese Inn",
  "Cabin Rental Agency",
  "Chalet",
  "Cottage",
  "Cottage Rental",
  "Cottage Village",
  "Group Accommodation",
  "Guest House",
  "Holiday Accommodation Service",
  "Holiday Apartment",
  "Holiday Apartment Rental",
  "Holiday Home",
  "Homestay",
  "Hostel",
  "Indoor Lodging",
  "Japanese Inn with Hot Spring",
  "Japanese Inns",
  "Lodge",
  "Lodging",
  "Log Cabins",
  "Motel",
  "Mountain Cabin",
  "Non-Smoking Holiday Home",
  "Pet-Friendly Accommodation",
  "Resort",
  "Self-Catering Accommodation",
  "Serviced Accommodation",
  "Timeshare Agency",
  "Travellers Lodge",
  "Vacation Home Rental Agency",
  "Vacation Rental",
  "Canoe & Kayak Tour Agency",
  "Cruise Line Company",
  "Cultural Tours Provider",
  "Farm Household Tour",
  "Golf Resort",
  "Helicopter Tour Agency",
  "Holiday Park",
  "Raft Trip Outfitter",
  "Recreational and Vacation Camps",
  "Rest Stop",
  "SCUBA Tour Agency",
  "Sightseeing Tour Agency",
  "Ski Holidays",
  "Ski Resort",
  "Sport Tour Agency",
  "Tour Agency",
  "Tour Operator",
  "Travel Agency",
  "Travel Aggregator",
  "Whale Watching Tour Agency",
  "Airline",
  "Airport",
  "Airport Shuttle Service",
  "Flights Search Site",
  "International Airport",
  "Lounge",
  "Regional Airport",
  "Travel lounge",
  "Airport Hotel",
  "Boutique Hotel",
  "Budget Hotel",
  "Business Hotel",
  "Capsule Hotel",
  "Castle Hotel",
  "Conference Hotel",
  "Extended Stay Hotel",
  "Family Hotel",
  "Hot Spring Hotel",
  "Hotel",
  "Hotel Supply Store",
  "Inn",
  "Love Hotel",
  "Luxury Hotel",
  "Wellness Hotel",
  "Airline Ticket Agency",
  "Balloon Ride Tour Agency",
  "Boat Tour Agency",
  "Bus Tour Agency",
  "Cruise Agency",
  "Cruise Travel Agency",
  "Tourist Attraction",
  "Tourist Information Center",
  "Visa and Passport Office",
  "Visa Consultant",
  "Coal Exporter",
  "Coal Supplier",
  "Coalfield",
  "Electric Utility Company",
  "Electrical Substation",
  "Energy Equipment and Solutions",
  "Energy Supplier",
  "Gas Company",
  "Gasfitter",
  "Green Energy Supplier",
  "Housing Utility Company",
  "Hydroelectric Power Plant",
  "Nuclear Power Company",
  "Nuclear Power Plant",
  "Oil & Natural Gas Company",
  "Oil and Gas Exploration Service",
  "Power Plant Consultant",
  "Power Station",
  "Solar Energy Company",
  "Solar Photovoltaic Power Plant",
  "Thermal Energy Company",
  "Utility Contractor",
  "Diesel Fuel Supplier",
  "Fuel Supplier",
  "Oil Refinery",
  "Oil Store",
  "Oilfield",
  "Petroleum Products Company",
  "Solid Fuel Company",
  "Water Purification Company",
  "Water Treatment Plant",
  "Water Utility Company",
  "Water Works",
  "Wind Farm",
  "Aeronautical Engineer",
  "Aerospace Company",
  "Air Force Base",
  "Air Taxi",
  "Aircraft Maintenance Company",
  "Aircraft Rental Service",
  "Aircraft Supply Store",
  "Airstrip",
  "Aviation Consultant",
  "Aviation Training Institute",
  "Boat Accessories Store",
  "Boat Cover Supplier",
  "Boat Dealer",
  "Boat Ramp",
  "Boat Storage Facility",
  "Boat Trailer Dealer",
  "Boatel",
  "Boating Club",
  "Boating Instructor",
  "Cruise Terminal",
  "Ferry Service",
  "Helicopter Charter",
  "Heliport",
  "Houseboat Rental Service",
  "Marina",
  "Outboard Motor Store",
  "Port Authority",
  "Port Operating Company",
  "Propeller Shop",
  "Sailing Event Area",
  "Sailmaker",
  "Shipbuilder",
  "Shipbuilding and Repair Company",
  "Shipyard",
  "Terminal point",
  "Yacht Broker",
  "Yacht Club",
  "Yakatabune",
  "Domestic Airport",
  "Free Parking Lot",
  "Parking Garage",
  "Parking Lot",
  "Parking Lot for Bicycles",
  "Parking Lot for Motorcycles",
  "Seaplane Base",
  "Tsukigime Parking Lot",
  "Valet Parking Service",
  "Auto Accessories Wholesaler",
  "Auto Air Conditioning Service",
  "Auto Body Parts Supplier",
  "Auto Body Shop",
  "Auto Chemistry Shop",
  "Auto Dent Removal Service",
  "Auto Electrical Service",
  "Auto Glass Shop",
  "Auto Machine Shop",
  "Auto Parts Manufacturer",
  "Auto Parts Market",
  "Auto Parts Store",
  "Auto Restoration Service",
  "Auto Spring Shop",
  "Auto Sunroof Shop",
  "Auto Tag Agency",
  "Auto Tune Up Service",
  "Auto Upholsterer",
  "Auto Wrecker",
  "Brake Shop",
  "Car Accessories Store",
  "Car Alarm Supplier",
  "Car Battery Store",
  "Car Detailing Service",
  "Car Equipment Accessories Store",
  "Car Factory",
  "Car Inspection Station",
  "Car Security System Installer",
  "Car Service",
  "Car Stereo Store",
  "Car Wash",
  "Driveshaft Shop",
  "Garage Equipment Wholesaler",
  "Hub Cap Supplier",
  "License Plate Frames Supplier",
  "Motorcycle Parts Store",
  "Racing Car Parts Store",
  "Tire Manufacturer",
  "Tire Shop",
  "Truck Parts Supplier",
  "Used Auto Parts Store",
  "Used Tire Shop",
  "Wheel Alignment Service",
  "Wheel Store",
  "Bicycle Rack",
  "Bicycle Rental Service",
  "Bicycle Repair Shop",
  "Bicycle Store",
  "Bicycle Wholesale",
  "Bike Accessories Store",
  "Used Bicycle Shop",
  "Acura Dealer",
  "Alfa Romeo dealer",
  "Aston Martin dealer",
  "Audi Dealer",
  "Auto Auction",
  "Auto Broker",
  "Auto Market",
  "Bentley dealer",
  "BMW Dealer",
  "Bugatti dealer",
  "Buick Dealer",
  "Cadillac Dealer",
  "Camper Shell Supplier",
  "Car Dealer",
  "Car Manufacturer",
  "Chevrolet Dealer",
  "Chrysler Dealer",
  "Citroen dealer",
  "Diesel Engine Dealer",
  "Dodge Dealer",
  "Ferrari dealer",
  "Fiat dealer",
  "Ford Dealer",
  "Genesis dealer",
  "GMC Dealer",
  "Honda Dealer",
  "Hyundai Dealer",
  "Infiniti Dealer",
  "Isuzu Dealer",
  "Jaguar Dealer",
  "Jeep Dealer",
  "Karma dealer",
  "Kia Dealer",
  "Lamborghini dealer",
  "Land Rover Dealer",
  "Lexus Dealer",
  "Lincoln dealer",
  "Maserati dealer",
  "Mayback dealer",
  "Mazda Dealer",
  "McLaren dealer",
  "Mercedes-Benz Dealer",
  "MINI dealer",
  "Mitsubishi Dealer",
  "Motor Vehicle Dealer",
  "Nissan Dealer",
  "Opel dealer",
  "Peugeot dealer",
  "Pontiac Dealer",
  "Porsche Dealer",
  "Renault dealer",
  "Rolls Royce dealer",
  "Saab Dealer",
  "Salvage Dealer",
  "Saturn Dealer",
  "SEAT dealer",
  "Skoda Dealer",
  "Smart Dealer",
  "Smartcar dealer",
  "Subaru Dealer",
  "Suzuki Dealer",
  "Tesla Showroom",
  "Toyota Dealer",
  "Truck Accessories Store",
  "Truck Dealer",
  "Truck Farmer",
  "Truck Stop",
  "Truck Topper Supplier",
  "Trucking Company",
  "Trucking School",
  "Used Car Dealer",
  "Used Truck Dealer",
  "Volkswagen Dealer",
  "Volvo Dealer",
  "BMW Motorcycle Dealer",
  "Car Racing Track",
  "Department of Motor Vehicles",
  "Ducati Dealer",
  "Harley-Davidson Dealer",
  "Kawasaki Motorcycle Dealer",
  "Moped Dealer",
  "Motor Scooter Dealer",
  "Motorcycle Dealer",
  "Motorcycle Driving School",
  "Motorcycle Equipment and Accessories Store",
  "Motorcycle Shop",
  "Motoring Club",
  "Off-Road Race Track",
  "Race Car Dealer",
  "Suzuki Motorcycle Dealer",
  "Triumph Motorcycle Dealer",
  "Used Motorcycle Dealer",
  "Yamaha Motorcycle Dealer",
  "ATV Dealer",
  "ATV Rental Service",
  "ATV Repair Shop",
  "Dump Truck Dealer",
  "Forklift Dealer",
  "Golf Cart Dealer",
  "Horse Trailer Dealer",
  "Mobile Home Dealer",
  "Mobile Home Park",
  "Mobile Home Rental Agency",
  "Mobile Home Supply Store",
  "Oldsmobile Dealer",
  "RV Dealer",
  "RV Storage Facility",
  "RV Supply Store",
  "Snowmobile Dealer",
  "Tractor Dealer",
  "Trailer Dealer",
  "Trailer Supply Store",
  "Utility Trailer Dealer",
  "Vehicle Examination Office",
  "Vehicle Exporter",
  "Vehicle Inspection",
  "Bus and Coach Company",
  "Bus Charter",
  "Bus Company",
  "Bus Ticket Agency",
  "Handicapped Transportation Service",
  "Limousine Service",
  "Metropolitan Train Company",
  "Minibus Taxi Service",
  "Mountain Cable Car",
  "Pedestrian Zone",
  "Railroad Company",
  "Railway Service",
  "Road Safety Town",
  "School Bus Service",
  "Suburban Train Line",
  "Taxi Service",
  "Taxi Stand",
  "Train Ticket Agency",
  "Train Ticket Counter",
  "Train Yard",
  "Transportation Escort Service",
  "Transportation Service",
  "Weigh Station",
  "Boat Rental Service",
  "Car Leasing Service",
  "Car Rental Agency",
  "Car Sharing Location",
  "Carpool",
  "Leasing Service",
  "Motorcycle Rental Agency",
  "Recreational Vehicle Rental Agency",
  "Scooter Rental Service",
  "Snowmobile Rental Service",
  "Trailer Rental Service",
  "Truck Rental Agency",
  "Van Rental Agency",
  "Alternative Fuel Station",
  "Auto Radiator Repair Service",
  "Auto Repair Shop",
  "Automobile Storage Facility",
  "Automotive Repair Equipment Wholesaler",
  "Boat Repair Shop",
  "Car Repair and Maintenance",
  "CNG Fittment Center",
  "Electric Motor Store",
  "Electric Vehicle Charging Station",
  "Engine Rebuilding Service",
  "Gas Station",
  "GPS Supplier",
  "LPG Conversion",
  "Mechanic",
  "Motor Scooter Repair Shop",
  "Motorcycle Repair Shop",
  "Muffler Shop",
  "Oil Change Service",
  "RV Repair Shop",
  "Scooter Repair Shop",
  "Self-Service Car Wash",
  "Smog Inspection Station",
  "Telematics Service",
  "Towing Equipment Provider",
  "Towing Service",
  "Tractor Repair Shop",
  "Trailer Repair Shop",
  "Train Repairing Center",
  "Transmission Shop",
  "Truck Repair Shop",
  "Tune Up Supplier",
  "Tuning Automobile",
  "Wheelchair Repair Service",
];
