import { FastifyPluginAsync } from "fastify";
import { routeOfCompanyVisit } from "./routeOfCompanyVisit";
import { routeOfCreateCompany } from "./routeOfCreateCompany";
import { routeOfDashboardStats } from "./routeOfDashboardStats";
import { routeOfDeleteEmailForBcc } from "./routeOfDeleteEmailForBcc";
import { routeOfGenerateReviewToken } from "./routeOfGenerateReviewToken";
import { routeOfGetCategories } from "./routeOfGetCategories";
import { routeOfGetCompanies } from "./routeOfGetCompanies";
import { routeOfGetCompanyById } from "./routeOfGetCompanyById";
import { routeOfReviewStats } from "./routeOfGetReviewStats";
import { routeOfGetVisitStats } from "./routeOfGetVisitsStats";
import { routeOfPutEmailForBcc } from "./routeOfPutEmailForBcc";
import { routeOfRemoveCompany } from "./routeOfRemoveCompany";
import { routeOfRestoreCompany } from "./routeOfRestoreCompany";
import { routeOfReviewSourceStats } from "./routeOfReviewSourceStats";
import { routeOfUpdateCompany } from "./routeOfUpdateCompany";
import { routeOfUpdateAlert } from "@/routes/company/routeOfUpdateAlert";
import { routeOfDeleteAlert } from "@/routes/company/routeOfDeleteAlert";
import { routeOfConvertToTest } from "./routeOfConvertToTest";
import { routeOfSwitchFingerprint } from "./routeOfSwitchFingerprint";
import { routeOfGetCompanyOwner } from "@/routes/company/routeOfGetCompanyOwner";

export const companyRoutes: FastifyPluginAsync = async (fastify) => {
  fastify.register(routeOfCreateCompany);
  fastify.register(routeOfGenerateReviewToken);
  fastify.register(routeOfGetCategories);
  fastify.register(routeOfGetCompanies);
  fastify.register(routeOfGetCompanyById);
  fastify.register(routeOfRemoveCompany);
  fastify.register(routeOfRestoreCompany);
  fastify.register(routeOfUpdateCompany);
  fastify.register(routeOfDashboardStats);
  fastify.register(routeOfReviewStats);
  fastify.register(routeOfDeleteEmailForBcc);
  fastify.register(routeOfPutEmailForBcc);
  fastify.register(routeOfReviewSourceStats);
  fastify.register(routeOfCompanyVisit);
  fastify.register(routeOfGetVisitStats);
  fastify.register(routeOfUpdateAlert);
  fastify.register(routeOfDeleteAlert);
  fastify.register(routeOfConvertToTest);
  fastify.register(routeOfSwitchFingerprint);
  fastify.register(routeOfGetCompanyOwner);
};
